### ISSUE TITLE
Add Contributing.md file as well as update the readme file

### ISSUE THREAD

**Issue by bhavesh1129** [swapnilsparsh/Rescue#10]
Hii @swapnilsparsh,
I would like to work on contributing.md as well as updating the present readme file by adding some cool elements which look amazing or gives a  cool/nice look.
Hope you like it!
Thankyou in advance

**Comment by swapnilsparsh** [comment]
That's great
You can work on this.

**Comment by bhavesh1129** [comment]
Thankyou @swapnilsparsh!
Is there any time period for submitting the PR?

**Comment by swapnilsparsh** [comment]
> Thankyou @swapnilsparsh!
> Is there any time period for submitting the PR?

No time period.
PR will be merged on first come first serve basis.
So anyone can work on this issue but first you have to tell that you are interested in the issue so that I can assign it to you.

**Comment by bhavesh1129** [comment]
Ok great!
Yeah, I would love to contribute to this issue.

**Comment by swapnilsparsh** [comment]
> Ok great!
> Yeah, I would love to contribute to this issue.

That's great.

**Comment by smriti1313** [comment]
Hello, i would be glad if you assign this to me. I am eager to help in such a good project.

**Comment by IshetaBansal** [comment]
Hi! 
I would love to work on a project like this. Very keen on working for Women Security with you. Thank you :)

**Comment by Himanshi2016** [comment]
Hello sir ! 
I also would like to work on this issue

**Comment by swapnilsparsh** [comment]
> Hello, i would be glad if you assign this to me. I am eager to help in such a good project.

@smriti1313  You can start your work.

**Comment by swapnilsparsh** [comment]
@IshetaBansal and @Himanshi2016 you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

**Comment by kanishkaa24** [comment]
Hello 
I would love to work on this issue.

**Comment by swapnilsparsh** [comment]
> Hello
> I would love to work on this issue.

Thank you for showing you interest in the project.
@kanishkaa24  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by smriti1313** [comment]
Can you tell me in detail about contributing.md? What shall be included in it? Also I have done readme part. So can i pull request of that part?

**Comment by swapnilsparsh** [comment]
> Can you tell me in detail about contributing.md? What shall be included in it? Also I have done readme part. So can i pull request of that part?

Keep all the necessary things that are there in contributing.md file and that's great that you have finished the Readme part.
But this issue is for both contributing.md file and Readme file, so when you are done with both the issues resolved then request a PR.

**Comment by smriti1313** [comment]
> 
> 
> > Can you tell me in detail about contributing.md? What shall be included in it? Also I have done readme part. So can i pull request of that part?
> 
> Keep all the necessary things that are there in contributing.md file and that's great that you have finished the Readme part.
> But this issue is for both contributing.md file and Readme file, so when you are done with both the issues resolved then request a PR.

@swapnilsparsh What sort of necessary things? It would be great if you could give an example or two. Thank you

**Comment by swapnilsparsh** [comment]
> > > Can you tell me in detail about contributing.md? What shall be included in it? Also I have done readme part. So can i pull request of that part?
> > 
> > 
> > Keep all the necessary things that are there in contributing.md file and that's great that you have finished the Readme part.
> > But this issue is for both contributing.md file and Readme file, so when you are done with both the issues resolved then request a PR.
> 
> @swapnilsparsh What sort of necessary things? It would be great if you could give an example or two. Thank you

1. Contribution (heading and some general info)
2. Pull Request Process
3. Code of Conduct
and etc.

**Comment by pankaj892** [comment]
Looks interesting I can work on this issue assign me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> Looks interesting I can work on this issue assign me @swapnilsparsh

It's already assigned to you.

**Comment by swapnilsparsh** [comment]
> Looks interesting I can work on this issue assign me @swapnilsparsh

Thank you for showing you interest in the project.
@pankaj892  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by bhavesh1129** [comment]
- **This is how now Readme.md file looks:**
![Readme](https://user-images.githubusercontent.com/54619203/103179846-09c3b280-48b6-11eb-8897-25cc64c8cb60.png)

- **This is how now Conributing.md file looks:**
![Contributing](https://user-images.githubusercontent.com/54619203/103179890-6b841c80-48b6-11eb-9ea2-e8bf9d16cbc7.png)

**Comment by swapnilsparsh** [comment]
@bhavesh1129 
Both the files are looking awesome.
Send a PR so I can merge it.

**Comment by swapnilsparsh** [comment]
Issue has been resolved by @smriti1313
