### ISSUE TITLE
Fix the GIF going under the Navbar in small screen

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#103]
![Annotation 2021-02-16 123400](https://user-images.githubusercontent.com/69387608/108029519-96d3ee00-7053-11eb-867f-32cc861db92a.png)

**Comment by sakshikhachane** [comment]
@swapnilsparsh I would like to work on this issue.

**Comment by saaiswetha** [comment]
I would like to contribute to this issue, am a part of GSSoC'21

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by swapnilsparsh** [comment]
@saaiswetha and @medhavi11 
You can start your work and soon I will be adding the level tag.

**Comment by saaiswetha** [comment]
there are no white spaces below the carousel while viewing in desktop.
<img width="942" alt="space" src="https://user-images.githubusercontent.com/55787747/110340919-cde46080-804f-11eb-87f7-6a6148a5646b.PNG">

**Comment by feni-katharotiya** [comment]
@swapnilsparsh Hello, I am gssoc participant and would like to work on this issue.

**Comment by swapnilsparsh** [comment]
@feni-katharotiya Already 2 people are working on it, so you have to wait for 3 days then if they are unable to resolve the issue or if they want more time then they can ask for it if they didn't ask it then it will be assigned to you.

**Comment by swapnilsparsh** [comment]
> there are no white spaces below the carousel while viewing in desktop.
> <img alt="space" width="942" src="https://user-images.githubusercontent.com/55787747/110340919-cde46080-804f-11eb-87f7-6a6148a5646b.PNG">

Check in mobile view

**Comment by saaiswetha** [comment]
@swapnilsparsh Have submitted a PR, do review it and let me know in case of any changes.

**Comment by saaiswetha** [comment]
@swapnilsparsh I have submitted a PR, do review it and let me know in case of any changes.

**Comment by mansijain980** [comment]
@sakshikhachane Please assign this issue to me . I am a GSSOC'21 participant .

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue

**Comment by sakshikhachane** [comment]
@simranbhalla3 Go ahead with this issue. Happy learning:)

**Comment by Ankita297** [comment]
@sakshikhachane  @swapnilsparsh  can i work on this ?

**Comment by swapnilsparsh** [comment]
> @sakshikhachane @swapnilsparsh can i work on this ?

Sure

**Comment by Ankita297** [comment]
@swapnilsparsh  @sakshikhachane  there is no white space probelm see however the gif is going below the navbar so may i correct it

**Comment by Ankita297** [comment]
![127 0 0 1_8000 - Google Chrome 05-04-2021 10_19_01](https://user-images.githubusercontent.com/67833077/113538308-86260a00-95f8-11eb-945f-50aeacf750bf.png)

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh @sakshikhachane there is no white space probelm see however the gif is going below the navbar so may i correct it

OK
