### ISSUE TITLE
Improve the women's laws html documentation

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#117]

**Comment by AishwaryaKaranth** [comment]
Can I work on this as part of GSSOC'21 ?

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by swapnilsparsh** [comment]
@AishwaryaKaranth and @medhavi11
You can start your work and soon I will be adding the level tag.

**Comment by DhanyaHegde01** [comment]
I would also like to work on this as part of Gssoc'21

**Comment by anish-cpu** [comment]
Hi Swapnil,
I would like to work on this issue as a GSSOC '21 participant. Please mark me as assignee.
Regards,
Anish

**Comment by Aarti002** [comment]
hey @swapnilsparsh can i work on this issue if it is not done yet as gssoc'21 participant

**Comment by feni-katharotiya** [comment]
@swapnilsparsh Hello, I am gssoc participant and would like to work on this issue.

**Comment by swapnilsparsh** [comment]
@DhanyaHegde01 @anish-cpu @Aarti002 @feni-katharotiya  Already 2 people are working on it, so you have to wait for 3 days then if they are unable to resolve the issue or if they want more time then they can ask for it if they didn't ask it then it will be  assigned to the person that ask first after that to the next person so that everyone will get the chance.

**Comment by feni-katharotiya** [comment]
@swapnilsparsh okay

**Comment by AishwaryaKaranth** [comment]
> @AishwaryaKaranth and @medhavi11
> You can start your work and soon I will be adding the level tag.

Submitted a PR #129

**Comment by mansijain980** [comment]
Is the issue solved if not i would like to do work on it . 
Please assign it to me.

**Comment by swapnilsparsh** [comment]
Thank you everyone for showing you interest in our project but we will be following the First Come First Serve basis and the person who is assigned to resolve the issue will get 3 days to resolve the issue and if the person want more time he/she have to ask for it ,if he/she is unable to do it then it will be assigned to the next person who wants to work on this issue.

**Comment by RiaKokate** [comment]
Hello @swapnilsparsh Can I be a part of this task. I would love to work for this.  
Thanks.

**Comment by simranbhalla3** [comment]
Hii . Can i work on this issue? I am a Gssoc participant

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. Thanks!

**Comment by sakshikhachane** [comment]
@simranbhalla3 Goaahead with the issue:)

**Comment by simranbhalla3** [comment]
@sakshikhachane I had some doubt, could you tell me what exactly i have to change? like the information regarding the laws or the way they are written (specifically the css?)

**Comment by Kavs-123** [comment]
Hey @simranbhalla3,
I am excited to work on this issue and perform the necessary changes!
Please allow me to do so

**Comment by Charanjeev-2k2** [comment]
Hi @sakshikhachane I am eager to contribute to this issue. Kindly assign it to me :)

**Comment by swapnilsparsh** [comment]
> Hey @simranbhalla3,
> I am excited to work on this issue and perform the necessary changes!
> Please allow me to do so

Work on it.

**Comment by mansijain980** [comment]
> Is the issue solved if not i would like to do work on it .
> Please assign it to me.

Can i proceed with this issue as i requested before Kavs-123 and really want to solve this .
Thanks

**Comment by swapnilsparsh** [comment]
> > Is the issue solved if not i would like to do work on it .
> > Please assign it to me.
> 
> Can i proceed with this issue as i requested before Kavs-123 and really want to solve this .
> Thanks

Sorry, I forgot to assign you, please look after other issues that need your help.
