### ISSUE TITLE
Fix register.html page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#118]
![Register Page](https://user-images.githubusercontent.com/69387608/110314996-9a450e80-802e-11eb-82de-0e684d9cf62d.png)

1. Change the text colour to some dark colour so that it can be visible easily.
2. Add a icon which can show and hide password in the password and confirm password both field.
3. Change the photo and use some photo relate to register page.

**Comment by deek121477** [comment]
Hey, I would love to contribute to this issue. Could you plz assign me?

**Comment by nilisha-jais** [comment]
I want to work on it as  a part of GSSOC

**Comment by RituCs** [comment]
Hello I want to work on this issue.Is it still open?

**Comment by nandini7637** [comment]
Hello sir I would like to contribute to this issue can you please assign me this?
I am  a GSSOC participant.

**Comment by Shivam-Shandilya1** [comment]
Hey!!! Can I give assisstance to your nice project as a GSSOC participant

**Comment by Amrutha-Obili** [comment]
Hey.. I would like to work on this issue as a GSSOC participant. Can you please assign it to me?

**Comment by saumyaparikh** [comment]
I would like to work on it as a GSSOC participant.

**Comment by parth-27** [comment]
Hey!!! I would like to work on this issue. Can you please assign it to me ??

**Comment by somya51p** [comment]
Hello, @swapnilsparsh! I would like to contribute to this issue. Can you please assign it to me?

**Comment by arbazalam01** [comment]
can i work on this issue as a GSSOC participant

**Comment by subhangi2731** [comment]
Please assign me this issue

**Comment by Sakshi0401** [comment]
Hello @swapnilsparsh I would like to work on it as a GSSOC participant. Can you please assign it to me ?

**Comment by Abhishek765** [comment]
Hello @swapnilsparsh I would like to contribute to this task as a GSSOC participant, Could you assign it to me?

**Comment by Siddharth1006** [comment]
Hey @swapnilsparsh!
I have a solution to your problem. If you can please assign the above issue to me!

**Comment by aanchalrakheja** [comment]
Hey! would love to contribute to this task as a participant of GSSOC'21. Please allow me to do so by assigning it to me.

**Comment by Aarti002** [comment]
hey @swapnilsparsh can i work on this issue under gssoc'21 participant i can work comfortably in html,css and django

**Comment by feni-katharotiya** [comment]
@swapnilsparsh  Hello, I am gssoc participant and would like to work on this issue.

**Comment by swapnilsparsh** [comment]
We will be following the First Come First Serve basis and the person who is assigned to resolve the issue will get 3 days to resolve the issue and if the person want more time he/she have to ask for it ,if he/she is unable to do it then it will be assigned to the next person who wants to work on this issue.

**Comment by sakshi21-03** [comment]
@swapnilsparsh , I am a GSSOC 2021 Participant, and i would like to work on this issue.

**Comment by somya12-coder** [comment]
Hello sir I would like to contribute to this issue can you please assign me this?
I am a GSSOC participant

**Comment by mansijain980** [comment]
@swapnilsparsh sir , i started work for this issue. Till tomorrow night , i will merge a pull request in it . 
Please assign it to me.

**Comment by swapnilsparsh** [comment]
> I want to work on it as a part of GSSOC

You have been assigned.

**Comment by nilisha-jais** [comment]
@swapnilsparsh sorry but I am facing an issue in setting up the project.....if you want you can assign the issue to the next person

**Comment by sakshikhachane** [comment]
> @swapnilsparsh sorry but I am facing an issue in setting up the project.....if you want you can assign the issue to the next person

@nilisha-jais What kind of issues you are facing? You can ping me on discord. The username - SAKSHI#0042

**Comment by aqua0** [comment]
I woud love to work on this issue as a gssco'21 participant

**Comment by tanishq-arya** [comment]
@swapnilsparsh I have changed some CSS and the svg graphic. I would like to work more on this under GSSOC. Please assign me this issue.
![Screenshot (949)](https://user-images.githubusercontent.com/77333275/110967678-ac031a80-837c-11eb-9ec5-4afeb6584013.png)

**Comment by sakshikhachane** [comment]
> @swapnilsparsh I have changed some CSS and the svg graphic. I would like to work more on this under GSSOC. Please assign me this issue.
> ![Screenshot (949)](https://user-images.githubusercontent.com/77333275/110967678-ac031a80-837c-11eb-9ec5-4afeb6584013.png)

As you have done most of the changes, you are been assigned. Please make a PR after doing the changes.
Happy learning:)

**Comment by tanishq-arya** [comment]
I have a question. I am not able to change the form or the header and footer because it uses materialize.ui so how should I proceed with that.

**Comment by sakshikhachane** [comment]
> I have a question. I am not able to change the form or the header and footer because it uses materialize.ui so how should I proceed with that.

Please ping me on discord. Username - SAKSHI#0042

**Comment by Pallavi-02** [comment]
Hey....i'm GSSoC'21 participant. Please assign me this issue.I would love to work on this.

**Comment by Avantika782** [comment]
Hey want to contribute to it. Can you assign it to me @swapnilsparsh

**Comment by yashkumar7889** [comment]
Hey, I'm GSSoC21 particioant. I would like to add icon which can show and hide password. Please assign this to me. I would love to work on this.
