### ISSUE TITLE
Improving the navbar

### ISSUE THREAD

**Issue by prisha-srivastava** [swapnilsparsh/Rescue#119]
I would like to improve the appearance of the navbar by making it more attractive and relocating the links in a better way. Contributing as a participant of GSSOC'21. Could you please assign it to me?

**Comment by saumyaparikh** [comment]
I would like to work on the navbar as a participant of GSSOC'21.

**Comment by Alleny244** [comment]
Hello
I am a GSSOC'21 participant
I would like to contribute in this issue.
 Could you please assign it to me?

**Comment by 2001asjad** [comment]
Hello
I am a GSSOC'21 participant . I would also like to work on this issue and on this project as well.
Thanks.

**Comment by kalpanapurohit** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by feni-katharotiya** [comment]
@prisha-srivastava . Hello, I am gssoc participant and would like to work on this issue.

**Comment by feni-katharotiya** [comment]
@swapnilsparsh Hello, I am gssoc participant and would like to work on this issue.

**Comment by swapnilsparsh** [comment]
We will be following the First Come First Serve basis and the person who is assigned to resolve the issue will get 3 days to resolve the issue and if the person want more time he/she have to ask for it ,if he/she is unable to do it then it will be assigned to the next person who wants to work on this issue.

**Comment by Shivam-Shandilya1** [comment]
Can I also work on this issue as Gssoc Participant?

**Comment by prisha-srivastava** [comment]
@swapnilsparsh I have made the changes and created the pull request. Kindly review it.

**Comment by devanshi-code** [comment]
Can i work on this issue?

**Comment by GVaruni19** [comment]
I would like to work on this issue

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.
