### ISSUE TITLE
Fix the typo error at Login Page.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#12]
![Screenshot_102](https://user-images.githubusercontent.com/69387608/103166659-5b365800-484a-11eb-839b-9861214a7865.png)

**Comment by musavveer** [comment]
Hi!
I would like to work on it.

**Comment by musavveer** [comment]
#13 Fixed a typo error

**Comment by swapnilsparsh** [comment]
Issue Resolved by @musavveer
