### ISSUE TITLE
A button to take you to the top of the page on every page. #GsSOC'21

### ISSUE THREAD

**Issue by kanishka8276** [swapnilsparsh/Rescue#123]
A top button on the bottom right corner to navigate to the top of the page for the women_rights.html and women_laws.html.
Please assign this to me. @swapnilsparsh 
#GsSOC'21

**Comment by 2001asjad** [comment]
@kanishka8276  I would like to work on this issue. I am GSSOC'21 participant and want to get started.. Thank You

**Comment by kanishka8276** [comment]
I am not the owner of this project. I am also a GsSOC'21 participant.

**Comment by shrishti-c** [comment]
A swift button to for smooth transition from bottom to up. I can do it. Please assign this to me.

**Comment by sakshikhachane** [comment]
> A top button on the bottom right corner to navigate to the top of the page for the women_rights.html and women_laws.html.
> Please assign this to me. @swapnilsparsh
> #GsSOC'21

Sure, please go ahead with this issue @kanishka8276.
Happy Learning :)

**Comment by kanishka8276** [comment]
Ok! 
@sakshikhachane Please add GsSOC'21 label. Thank you ☺️
