### ISSUE TITLE
Suggestion for helpline_numbers.html

### ISSUE THREAD

**Issue by kanishka8276** [swapnilsparsh/Rescue#124]
Linking the heading "women helpline numbers" to the pdf which contains all the women helpline numbers and is downloaded as soon as the link "women helpline numbers" is clicked for the future reference of the user.
Please assign this to me. @swapnilsparsh 
#GsSOC'21

**Comment by mansijain980** [comment]
@swapnilsparsh .......I can work on it easily as i know full stack development . Please assign it to me .

**Comment by swapnilsparsh** [comment]
> Linking the heading "women helpline numbers" to the pdf which contains all the women helpline numbers and is downloaded as soon as the link "women helpline numbers" is clicked for the future reference of the user.
> Please assign this to me. @swapnilsparsh
> #GsSOC'21

I don't think attaching a pdf is a nice option or you can add all the numbers on the website only.
If you are comfortable adding all the the women helpline numbers on website only then kindly let me know so I can assign you this issue.

**Comment by sakshikhachane** [comment]
> I don't think attaching a pdf is a nice option or you can add all the numbers on the website only.
> If you are comfortable adding all the the women helpline numbers on website only then kindly let me know so I can assign you this issue.

@kanishka8276 Can you please tell this so that we can assign this to you?

**Comment by kanishka8276** [comment]
Actually I am already working on 2 issues in this project. So I may not be able to do this in 3 days. But later I can do it.

**Comment by sakshikhachane** [comment]
Okay, no problem. @kanishka8276.
@mansijain980 Would you like to take on this issue?

**Comment by mansijain980** [comment]
@sakshikhachane Yes maam sure . I  would like to do work on it .

**Comment by sakshikhachane** [comment]
Assigned to you @mansijain980.
Happy learning:)

**Comment by mansijain980** [comment]
@sakshikhachane i have done this almost .....i will commit PR soon.

**Comment by sakshikhachane** [comment]
Yes, @mansijain980 take your time. If you require more time then do tell us :)

**Comment by sakshikhachane** [comment]
@mansijain980 Any updates?

**Comment by mansijain980** [comment]
@sakshikhachane Yes ma'am , work is almost done . Actually due to class projects , there was some delay . Most probably till tomorrow i will request u a PR . 
THANKS.

**Comment by mansijain980** [comment]
@sakshikhachane ma'am please review it and merge the pull request.
Thanks.

**Comment by coding-geek21** [comment]
I would like to work on this issue @sakshikhachane @swapnilsparsh Can you please assign me?

**Comment by mansijain980** [comment]
@sakshikhachane @swapnilsparsh @coding-geek21 i m doing work on this issue and will commit a PR tomorrow.
Thanks.

**Comment by swapnilsparsh** [comment]
> @sakshikhachane @swapnilsparsh @coding-geek21 i m doing work on this issue and will commit a PR tomorrow.
> Thanks.

It's almost 1 month you are working on this issue and there is no need of this issue to be resolved right now so I am closing it for now..
Sorry for the inconvenience caused

**Comment by farseenmanekhan1232** [comment]
what if the helpline number changes according to the location of the person .

**Comment by farseenmanekhan1232** [comment]
Even If I am a GSSOC Participant , i would like to work on this issue regardless of Time required or Points .
If we could brainstorm about this issue here or in discord channel , it would be great .
