### ISSUE TITLE
Improve the Documentation

### ISSUE THREAD

**Issue by 2001asjad** [swapnilsparsh/Rescue#127]
In the attached screenshot , the footer doesn't have the correct punctuation and we can also improve the grammer. It is always an important aspect of any website. I would love to work on this issue .

Moreover we can work on the CSS as well to enhance the text.

PS: I want to get started with this great project for GSSOC 21 and help it to grow a lot.

![Capture](https://user-images.githubusercontent.com/60435499/110605338-0b133480-81af-11eb-913e-cd196b05b468.PNG)

**Comment by Tushar1337** [comment]
can you assign this to me so that I can make a pull request?

**Comment by sakshikhachane** [comment]
Hey @2001asjad,
You can create 1 separate issue for improving the design of the footer. 
For this issue, add more content in the footer and improve the grammatical mistakes.

I am assigning this issue to you. Happy learning:)

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.
