### ISSUE TITLE
Improve the footer part by adding contact details at the footer part with social media handles icons 

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#131]
**Describe the bug**
----
- A clear and concise description of what the bug is.

**To Reproduce**
----
- Steps to reproduce the behavior:

**Expected behavior**
-----
- A clear and concise description of what you expected to happen.

**Possible solution**
----
- Describe the solution you thought of.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by coding-geek21** [comment]
Hello @swapnilsparsh  @U-c0de  @Assertor1   I just saw the footer without any contact details , i added some icons like linkedin, mail , facebook, twitter and also made improvements on footer and added copyrights at the end 
Can you please assign this to me so that i can create a pull request on this
I'm a GSSoC'21 participant .

**Comment by vanshikapandey** [comment]
I am interested in working in this issue. I can make a interactive footer. Please assign this issue to me as a GSSOC'21 participant

**Comment by coding-geek21** [comment]
I have already worked on this issue and i'm just waiting for the issue to get assigned for me and i'm also GSSOC'21 participant

**Comment by swapnilsparsh** [comment]
> Hello @swapnilsparsh @U-c0de @Assertor1 I just saw the footer without any contact details , i added some icons like linkedin, mail , facebook, twitter and also made improvements on footer and added copyrights at the end
> Can you please assign this to me so that i can create a pull request on this
> I'm a GSSoC'21 participant .

Actually there is no social media handles of our project and for our personal social media handles that are given in devlopers page only.
If I am missing someting , please tell me or attach a photo of it so I can relate it else I have to close this issue.

**Comment by coding-geek21** [comment]
Hello @swapnilsparsh  Actually there was no contact us page for the website , Contact us page helps people having queries to ask or contact the team so i guess contact us page will help people to contact the admin of the website if they have any issues or if they want to know something. and there was no copyrights for the website i just improved the footer by adding it

**Comment by sakshikhachane** [comment]
Hey @coding-geek21,
Go ahead with the issue. Happy learning:)

**Comment by coding-geek21** [comment]
Thank you once again for this opportunity :) @sakshikhachane

**Comment by sakshikhachane** [comment]
@coding-geek21 Any updates?

**Comment by coding-geek21** [comment]
Yes @sakshikhachane  i will be creating pull request by today ,

**Comment by coding-geek21** [comment]
hello @sakshikhachane I have completed the footer part of home.html page i have to change the same for other pages also
so can i do the pull request tomorrow 

![image](https://user-images.githubusercontent.com/53329034/111359954-2d76e780-86b2-11eb-8cfc-5e246ff047c3.png)

**Comment by coding-geek21** [comment]
Hello @sakshikhachane  i have a doubt , I have already made a pull request for another issue  which is not merged yet, so will i be able to  create a PR for this issue now?

**Comment by sakshikhachane** [comment]
@coding-geek21 Please ping me on discord. Username - SAKSHI#0042. I need to discuss with you regarding the footer also. Discussing here won't be a good option.

**Comment by coding-geek21** [comment]
ok @sakshikhachane

**Comment by coding-geek21** [comment]
@sakshikhachane  can you please add the level tag for this issue , because there are points for each level
