### ISSUE TITLE
Modification in website UI [ GSSoC' 21 ]

### ISSUE THREAD

**Issue by vineetsingh0809** [swapnilsparsh/Rescue#133]
Hey there,
I want to improve the UI of the website for a better look and output and I am so excited to contribute to this project. 
Kindly assign me this issue, by this, I will be able to continue my work.

**Comment by flyingsonu122** [comment]
Can you tell me where is it hosted @swapnilsparsh

**Comment by sakshikhachane** [comment]
Hey @vineetsingh0809,
Which pages are you thinking of enhancing the UI? Can you elaborate more about it?

**Comment by swapnilsparsh** [comment]
> Can you tell me where is it hosted @swapnilsparsh

Website is not live so you have to run it on  you local server.

**Comment by vineetsingh0809** [comment]
Hey @sakshikhachane ...
I have been already forked and cloned this project on my local system and I am looking for the opportunity to work on this project.
If you will assign me this issue, I'll try to make this website more attractive and better.

**Comment by flyingsonu122** [comment]
> > Can you tell me where is it hosted @swapnilsparsh
> 
> Website is not live so you have to run it on you local server.

alright 👍  @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> Hey @sakshikhachane ...
> I have been already forked and cloned this project on my local system and I am looking for the opportunity to work on this project.
> If you will assign me this issue, I'll try to make this website more attractive and better.

Which pages are you thinking of enhancing the UI? Can you elaborate more about it?

**Comment by sakshikhachane** [comment]
> > Hey @sakshikhachane ...
> > I have been already forked and cloned this project on my local system and I am looking for the opportunity to work on this project.
> > If you will assign me this issue, I'll try to make this website more attractive and better.
> 
> Which pages are you thinking of enhancing the UI? Can you elaborate more about it?

@vineetsingh0809 Can you please tell this so that we could assign you this issue?

**Comment by vineetsingh0809** [comment]
Hey @sakshikhachane & @swapnilsparsh .....
I need your guidance in this because I have cloned this in my system but as of now I am not able to make the website visible.
So please tell me how can I see the main website?
By this, I can start my further work on this issue.

**Comment by sakshikhachane** [comment]
@vineetsingh0809 Please refer to the installations step mentioned in the `readme.MD` file.

**Comment by MuskanV2001** [comment]
Hii there, I want to work on this issue as a GSSoC'21 participant. 
I wish to modify the website's UI, the home page specifically. I have thought of redesigning the footer and the navigation bar and making some other edits to enhance website's presentation.
Please assign me this issue.

**Comment by sakshikhachane** [comment]
Hey @vineetsingh0809,
Were you able to do the set up locally?

**Comment by vineetsingh0809** [comment]
> Hey @vineetsingh0809,
> Were you able to do the setup locally?

Hey, @sakshikhachane I did it and I saw the navigation bar is not looking that good so I want to work to make the navigation bar attractive.
![Capture](https://user-images.githubusercontent.com/75788774/111305103-8a57ab00-867c-11eb-8c8c-e307a8aca51d.PNG)


And 2nd thing I was thinking that when we are tapping any button in the navigation bar, it should be open in a new tab......
so should I start working on it?

**Comment by sakshikhachane** [comment]
@vineetsingh0809 Can you please show the sample of a design you are planning to make for the navigation bar?

**Comment by RiaKokate** [comment]
Hey @swapnilsparsh 
I could work on designing a logo for your project. I could share some of my ideas .Respond if you would like to have it on you project. Thanks

**Comment by sakshikhachane** [comment]
> Hey @swapnilsparsh
> I could work on designing a logo for your project. I could share some of my ideas .Respond if you would like to have it on you project. Thanks

Hey @RiaKokate,
Let's discuss the ideas in the discussions section :)

**Comment by vineetsingh0809** [comment]
> @vineetsingh0809 Can you please show the sample of a design you are planning to make for the navigation bar?

Yes Sure
