### ISSUE TITLE
less instructions and wrong links in Contributing.md

### ISSUE THREAD

**Issue by flyingsonu122** [swapnilsparsh/Rescue#137]
hey @swapnilsparsh , there are less instructions in and wrong links [Contributing.md](https://github.com/flyingsonu122/Rescue/blob/master/Contributing.md)
want to improve it

**Comment by swapnilsparsh** [comment]
> hey @swapnilsparsh , there are less instructions in and wrong links [Contributing.md](https://github.com/flyingsonu122/Rescue/blob/master/Contributing.md)
> want to improve it

Can you tell where less instructions are given ?

**Comment by flyingsonu122** [comment]
> > hey @swapnilsparsh , there are less instructions in and wrong links [Contributing.md](https://github.com/flyingsonu122/Rescue/blob/master/Contributing.md)
> > want to improve it
> 
> Can you tell where less instructions are given ?

you have not written about creating a new branch

**Comment by flyingsonu122** [comment]
6th step is missing

**Comment by flyingsonu122** [comment]
@swapnilsparsh can I make some best possible changes

**Comment by flyingsonu122** [comment]
@sakshikhachane now merge the PR

**Comment by swapnilsparsh** [comment]
Issue resolved by @flyingsonu122 #141
