### ISSUE TITLE
.gitignore file

### ISSUE THREAD

**Issue by SubhradeepSS** [swapnilsparsh/Rescue#14]
We can add a .gitignore file for the project so that changes in unnecessary files are not tracked in git like pycache, the database file-db.sqlite3 etc.
(work for DWOC)

**Comment by Bijay555** [comment]
@SubhradeepSS  I want to do this. Please can you assign me?

**Comment by SubhradeepSS** [comment]
> 
> 
> @SubhradeepSS I want to do this. Please can you assign me?

I am not the admin of this project. Actually I opened this issue for myself to work for DWOC.

**Comment by Bijay555** [comment]
@SubhradeepSS other cannot make issue, bro

**Comment by SubhradeepSS** [comment]
> 
> 
> @SubhradeepSS other cannot make issue, bro

Oh didn't knew that

**Comment by swapnilsparsh** [comment]
Hey @SubhradeepSS 

Its great that you noticed the issue and raised it but you should have asked me to raise the issue and then you can ask me to assign the issue to you. But no problem as there are only 2 people who are interested in this issue so both of you can look after this issue.
Good Luck 👍🏼

**Comment by SubhradeepSS** [comment]
> 
> 
> Hey @SubhradeepSS
> 
> Its great that you noticed the issue and raised it but you should have asked me to raise the issue and then you can ask me to assign the issue to you. But no problem as there are only 2 people who are interested in this issue so both of you can look after this issue.
> Good Luck 👍🏼

Oh, will keep that on mind from next time

**Comment by swapnilsparsh** [comment]
> > Hey @SubhradeepSS
> > Its great that you noticed the issue and raised it but you should have asked me to raise the issue and then you can ask me to assign the issue to you. But no problem as there are only 2 people who are interested in this issue so both of you can look after this issue.
> > Good Luck 👍🏼
> 
> Oh, will keep that on mind from next time

Resolve the conflicts and resend the PR
