### ISSUE TITLE
create Discussions here on GitHub

### ISSUE THREAD

**Issue by flyingsonu122** [swapnilsparsh/Rescue#140]
create [Discussions](https://github.com/swapnilsparsh/Rescue/discussions) here on GitHub for discussing any changes to this project

It is very easy to discuss here rather on Discord

**Comment by flyingsonu122** [comment]
@swapnilsparsh please go for it

**Comment by sakshikhachane** [comment]
@flyingsonu122 Sure! We will do that. Thanks for suggesting :)

**Comment by flyingsonu122** [comment]
> @flyingsonu122 Sure! We will do that. Thanks for suggesting :)

@sakshikhachane Your discord link is not working, paste the invitation link
