### ISSUE TITLE
Faulty and Outdated packages in requirements.txt file

### ISSUE THREAD

**Issue by Aditya201551** [swapnilsparsh/Rescue#142]
@swapnilsparsh 

There were many faulty and outdated packages found in the requirements.txt file that caused errors in the functioning of the site(locally) but I have fixed all the issues with the outdated and faulty packages so I would like to resolve this issue with my PR

ThankYou(GSSOC 2021 participant)

**Comment by sakshikhachane** [comment]
Hey @Aditya201551,
For now, this isn't required. So I am closing this issue.
You can come up with new issues and we will be assigning the issue happily if relevant.
