### ISSUE TITLE
Update Contributions in readme !!

### ISSUE THREAD

**Issue by rohank2502** [swapnilsparsh/Rescue#144]
Will like to add the feature will will update the contributors list automatically ! I have used this in my own repository for demo you can visit that  https://github.com/rohank2502/Learn-GITHUB

**Comment by sakshikhachane** [comment]
@rohank2502 Go ahead with the issue. Happy learning :)

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Go ahead with the issue. Happy learning :)

Thanks !!
