### ISSUE TITLE
Adding content to the home page by adding objective or 'mission and vision' at the home page 

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#146]
**Is your feature request related to a problem? Please describe.**
----
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by sakshikhachane** [comment]
@coding-geek21 Go ahead with this issue. Happy learning :)

**Comment by coding-geek21** [comment]
Whoa! @sakshikhachane  Thanks a lot :)

**Comment by Fpj-11** [comment]
I am a gssoc'21 participant. I would like to work on this issue.
