### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kanchi12P** [swapnilsparsh/Rescue#151]
**Describe the bug**
spelling mistake in a file.
**Possible solution**
instead of "security" it's written "securoty" in the file in one place.
- Describe the solution you thought of.
I would like to correct it.

**Additional context**
I am gssoc'21 participant .
**Please assign this to me**.

**Comment by swapnilsparsh** [comment]
> **Describe the bug**
> spelling mistake in a file.
> **Possible solution**
> instead of "security" it's written "securoty" in the file in one place.
> 
> * Describe the solution you thought of.
>   I would like to correct it.
> 
> **Additional context**
> I am gssoc'21 participant .
> **Please assign this to me**.

Can you tell in which file there is spelling mistake ?

**Comment by kanchi12P** [comment]
in Documentation/women_safety_laws.md
in the first line after that image of international womens day

**Comment by kanchi12P** [comment]
please assign it to me

**Comment by Avantika782** [comment]
hey, I'm a GSSOC participant please assign this to me;)
