### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by khanfarhan10** [swapnilsparsh/Rescue#153]
Deploy the Repository to Heroku/Any other Suitable Platform.

- Optimize for Performance
- Scale the WebApp

**Comment by swapnilsparsh** [comment]
Ok, I will be doing that.

**Comment by khanfarhan10** [comment]
@swapnilsparsh This repo is of no practical use if this project is not implemented in a real working website. Any updates?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh This repo is of no practical use if this project is not implemented in a real working website. Any updates?

It will be deployed soon.
