### ISSUE TITLE
Whatsapp instead of E-mail

### ISSUE THREAD

**Issue by sonal251001** [swapnilsparsh/Rescue#154]
**Is your feature request related to a problem? Please describe.**
----
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- Hey I think there is a problem with sending an email to the trusted ones.

**Describe the solution you'd like**
---- My solution is what if we can send whatsapp messages to the closed one because as much as people are active on whatsapp they are not anywhere . and anyone's first close ones would be parents and may be some parents don't know how to check mail but they can surely check whatsapp.
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
---- I don't know how to implement it. I am a GSSoC participant was scrolling through projects so thought of this!
- Add any other context or screenshots about the feature request here.

**Comment by swapnilsparsh** [comment]
@sonal251001 Work on this issue and add a alternate to the whatsapp message if any user does not have account on whatsapp then message should go on email and SMS both.

**Comment by sakshikhachane** [comment]
@sonal251001 Any updates on the issue?

**Comment by sonal251001** [comment]
No. I'm sorry but I wrote above that I don't know how to do it. I'll do it if anyone can guide me.

**Comment by sakshikhachane** [comment]
@sonal251001 Okay! No problem.

**Comment by Tarun-Kamboj** [comment]
I think we can do it using pywhatkit. Can I try this one? @sakshikhachane

**Comment by sakshikhachane** [comment]
@Tarun-Kamboj Go ahead with the issue. Happy learning:)

**Comment by Tarun-Kamboj** [comment]
I've implemented sending whatsapp messages to the contacts of the user.
Here are the changes that I've made. 

1. User will now also be adding the the mobile numbers of their contacts.

| ![Capture3](https://user-images.githubusercontent.com/56023742/112260495-06ab4900-8c90-11eb-92ed-d4c8378a1bfc.PNG) | ![Capture4](https://user-images.githubusercontent.com/56023742/112260570-2b9fbc00-8c90-11eb-9014-5977c87840af.PNG) |
|---|---|

2. Modified the views, form and model accordingly.
3. Added a script to send whatsapp messages.
- It sends a message to one contact per minute. I know it's quite slow but it was sometimes failing to send the message if I kept the time lower than that. See the pic below for reference. 
<p align="center"><img src="https://user-images.githubusercontent.com/56023742/112260892-d0ba9480-8c90-11eb-97f3-c157d3e34040.PNG"></p>

- If the number is on whatsapp then it sends the message successfully. 
<p align="center"><img src="https://user-images.githubusercontent.com/56023742/112260990-f5167100-8c90-11eb-8a57-9f87dc0b7719.PNG"></p>

- If the number is not on whatsapp then it simply shows the following message and proceeds to the next number.
<p align="center"><img src="https://user-images.githubusercontent.com/56023742/112261079-23944c00-8c91-11eb-9f9c-e9bbc6a889d5.PNG"></p>

**Comment by sakshikhachane** [comment]
@Tarun-Kamboj Great work! Please make a PR so that if there are any changes, then they can be suggested.

**Comment by Tarun-Kamboj** [comment]
> @Tarun-Kamboj Great work! Please make a PR so that if there are any changes, then they can be suggested.

Done @sakshikhachane, please review.
