### ISSUE TITLE
[GSSoC'21] To enhance the 'create emergency contact page' with css and bootstrap.

### ISSUE THREAD

**Issue by zaverisanya** [swapnilsparsh/Rescue#157]
I am a participant of GSSoC'21 and I feel that the 'create emergency contact page' can be made better looking by applying CSS and Bootstrap. Please allow me to make changes in `Rescue/main_app/templates/main_app/create_contact.html` to improve the UI.

@SubhradeepSS @flyingsonu122 Please let me know if I can work on this issue or not.

**Comment by sakshikhachane** [comment]
Hey @zaverisanya,
Go ahead with the issue. Happy learning:)

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue

**Comment by mansijain980** [comment]
@sakshikhachane can i work on this issue?

**Comment by mansijain980** [comment]
> @sakshikhachane can i work on this issue?

Ma'am please let me know i want to work on it .

**Comment by swapnilsparsh** [comment]
@mansijain980 Do you want to work on this ?

**Comment by mansijain980** [comment]
@swapnilsparsh I would like to do do work on this . Please assign this to me .
Thanks .

**Comment by mansijain980** [comment]
Can i add an  image in middle of page ?

**Comment by swapnilsparsh** [comment]
> Can i add an image in middle of page ?

You can try adding the image sideways if it doesn't work then try it in middle.

**Comment by mansijain980** [comment]
I am thinking of putting rescue logo in page as it can be weird if i put a different image.
Please tell me as with image it will look attractive.

**Comment by swapnilsparsh** [comment]
> I am thinking of putting rescue logo in page as it can be weird if i put a different image.
> Please tell me as with image it will look attractive.

Use images related to creating contacts or you can look after different illustrations that are there.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by sakshikhachane** [comment]
Hey @srishtij2000,
Currently, @mansijain980 is working on this. You can look for other issues or create your own issue. Your ideas to enhance this project are always welcomed :)

**Comment by coding-geek21** [comment]
@sakshikhachane @swapnilsparsh Can I work on this issue?  I will try to complete within 2 days

**Comment by mansijain980** [comment]
@coding-geek21  This is already done only i have to resolve the conflicts which will take hardly a hour .
I will resolve this conflict by today @sakshikhachane @swapnilsparsh 
Thanks.

**Comment by coding-geek21** [comment]
@swapnilsparsh Can i work on this?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Can i work on this?

@mansijain980 already working on the project.
