### ISSUE TITLE
Location Alert based on IP Address

### ISSUE THREAD

**Issue by jainayush362** [swapnilsparsh/Rescue#158]
**Is your feature request related to a problem? Please describe.**
----
- In any type of emergency, the Location of Victim plays a very crucial role. In India, most of the ISP's provide Dynamic IP Address i.e. it keeps changing as you move. So it will be good if one can use it to detect and alert about the location of victim also.

**Describe the solution you'd like**
----
- Using the IP Address we can automatically detect the Location using existing open source python libraries and then send it along with the emergency alert that includes location of victim too.

@swapnilsparsh @sakshikhachane If you find it useful and related then please assign me this so that I can start working on it. Once implemented, I think this will come out to be an amazing feature. I hope you will label it under GSSoc21 and assign me this.

**Comment by swapnilsparsh** [comment]
@jainayush362 Work on it

**Comment by jainayush362** [comment]
> @jainayush362 Work on it

Thanks..... I have started working on it.

**Comment by Furquan712** [comment]
i would like to work on this , will you assign me

**Comment by Furquan712** [comment]
@swapnilsparsh  any update?? i want to work

**Comment by sakshikhachane** [comment]
Yes @Furquan712,
Go ahead with the issue.
