### ISSUE TITLE
Improve the format of email message

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#159]
Deliverable -
- [ ]  On clicking the `EMERGENCY!` button, the mail is sent to the saved contacts. 
    Modify the format and design of the message sent through the mail.

**Comment by sakshikhachane** [comment]
Sure @AshuKV. Go ahead with the issue.
Happy learning :)

**Comment by sakshikhachane** [comment]
@AshuKV Any updates on the issue?

**Comment by AshuKV** [comment]
Hey @sakshikhachane, I am currently working on the issue. Can you please add another contributors to work on the same issue with me.

**Comment by sakshikhachane** [comment]
@AshuKV This issue doesn't require more contributors as it is not that tough and consists of the modification of UI format.

**Comment by sakshikhachane** [comment]
@nandini040 Go ahead with the issue. Happy learning:)

**Comment by nandini040** [comment]
@ sakshikhachane what i have to do i am little bit confused

**Comment by sakshikhachane** [comment]
Hey @nandini040,
Have you done the local setup? When you click on `EMERGENCY!` button, the mail will be sent to the emergency contacts that you have added. So, this issue is about modifying the format of the email message that is the display of the message that will be sent.

**Comment by coding-geek21** [comment]
Hey @sakshikhachane  i would like to work on this issue can you please assign me :)

**Comment by mansijain980** [comment]
@sakshikhachane Can i work on this issue?

**Comment by swapnilsparsh** [comment]
@nandini040 Any updates on the issue ?

**Comment by nandini040** [comment]
> @nandini040 Any updates on the issue ?

I am getting some issue in doing local setup.

**Comment by swapnilsparsh** [comment]
> > @nandini040 Any updates on the issue ?
> 
> I am getting some issue in doing local setup.

What issue are you facing, can you tell ?

**Comment by sakshikhachane** [comment]
@nandini040 Any updates?

**Comment by coding-geek21** [comment]
@swapnilsparsh I would like to work on this issue, Can you please assign me ,Thank you!
