### ISSUE TITLE
Make login page similar to register page

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#160]
Deliverable -
- [ ] The login page and register page are currently having different designs. Make UI of login page similar to that of register page.

**Comment by manasivaraiya** [comment]
Can I try working on this?
I am a participant of gssoc'21

**Comment by sakshikhachane** [comment]
Sure @manasivaraiya. Go ahead with the issue. Happy learning :)

Hey @AshuKV, we are going FCFS and each contributor is assigned for 3 days and if the contributor is not able to submit PR within 3 days then it will be assigned to the next person. Meanwhile, you can look for other issues or open up a new issue.

**Comment by manasivaraiya** [comment]
> Sure @manasivaraiya. Go ahead with the issue. Happy learning :)
> 
> Hey @AshuKV, we are going FCFS and each contributor is assigned for 3 days and if the contributor is not able to submit PR within 3 days then it will be assigned to the next person. Meanwhile, you can look for other issues or open up a new issue.

I had created a PR yesterday! lemme know if there are any more changes required.

**Comment by mansijain980** [comment]
@sakshikhachane Can i work on it?

**Comment by ambivert-sam** [comment]
Hey ! @AshuKV  I'm participant of GSSoC'21 I would like to contribute to this issue 
can you please assign it to me

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue

**Comment by mansijain980** [comment]
> @sakshikhachane Can i work on it?

Please may i know !!
Thanks.

**Comment by swapnilsparsh** [comment]
@mansijain980 Work on it.

**Comment by swapnilsparsh** [comment]
@mansijain980 Any updates ?

**Comment by mansijain980** [comment]
@swapnilsparsh sir actually i m working on three issues of this project as i have a keen interest in doing so . DAy after tomo i will complete this and commit a PR. Only some modifications left .
Thanks .

**Comment by mansijain980** [comment]
Can i change the fonts ?

**Comment by swapnilsparsh** [comment]
> Can i change the fonts ?

Font name ?

**Comment by mansijain980** [comment]
![image](https://user-images.githubusercontent.com/63226239/114770695-565dcb80-9d89-11eb-8ac5-02e2dabc9258.png)
this one.

**Comment by swapnilsparsh** [comment]
> ![image](https://user-images.githubusercontent.com/63226239/114770695-565dcb80-9d89-11eb-8ac5-02e2dabc9258.png)
> this one.

You can try using Product Sans rather than this.

**Comment by coding-geek21** [comment]
@sakshikhachane @swapnilsparsh Can I work on this issue? I will try to complete within 2 days

**Comment by mansijain980** [comment]
@coding-geek21 This is already done only i have to resolve the conflicts which will take hardly  a hour . 
I will resolve this conflict by today @sakshikhachane @swapnilsparsh 
Thanks

**Comment by mansijain980** [comment]
@sakshikhachane 
![image](https://user-images.githubusercontent.com/63226239/118353476-03dc1e80-b584-11eb-833c-dcc8687473e0.png)
![image](https://user-images.githubusercontent.com/63226239/118353504-23734700-b584-11eb-81de-dc9a77c24b43.png)
Can u please tell me why this error occur . For resolving issue og this branch i.e. login branch i pull it bt it is showing this . 
Please help me out ....

**Comment by mansijain980** [comment]
![image](https://user-images.githubusercontent.com/63226239/118353572-8e248280-b584-11eb-9077-629e051064f7.png)
or active this link please so that i can directly resolved them.
Thanks

**Comment by swapnilsparsh** [comment]
@mansijain980 There is some error from your side as you have to rebase the code to the master and then resolve the conflict.

**Comment by mansijain980** [comment]
![image](https://user-images.githubusercontent.com/63226239/119257097-6adf8000-bbe1-11eb-8bb8-62e7b528719d.png)
![image](https://user-images.githubusercontent.com/63226239/119257113-7af75f80-bbe1-11eb-9384-572bfb9eb0bc.png)
can u tell me which format u want ?
LIke register page is having first image so i should make it same as register page ?

**Comment by swapnilsparsh** [comment]
@mansijain980 Sorry for the inconvenience cause, this issue has been resolved.
