### ISSUE TITLE
Improve women_right.md documentation 

### ISSUE THREAD

**Issue by Diksha-11** [swapnilsparsh/Rescue#161]
I am a participant of GSSOC'21. 
I want improve women_right.md documentation by adding an introductory paragraph into it.

I request @swapnilsparsh sir to assign me this issue.

**Comment by RiaKokate** [comment]
Hello @swapnilsparsh.
I hope you are fine and doing well.
I am a GSSOC'21 participant and would like to contribute to this project. Could you please assign it to me.

**Comment by swapnilsparsh** [comment]
There is no need to improve the documentation right now.
