### ISSUE TITLE
Improving the UI of register and login with columns.

### ISSUE THREAD

**Issue by Tarun-Kamboj** [swapnilsparsh/Rescue#164]
**Is your feature request related to a problem? Please describe.**
----
- Yes, currently the register and login pages shows content in a single column like this
![Screenshot (200)](https://user-images.githubusercontent.com/56023742/111427152-abbba400-871b-11eb-8bb3-2d59b39b5005.png)

**Describe the solution you'd like**
----
- These pages should look something like this
![Screenshot (203)](https://user-images.githubusercontent.com/56023742/111427228-d279da80-871b-11eb-97df-cd79efbd911d.png)

**Additional context**
----
- Please assign this issue to me. I'm a gssoc21 participant.

**Comment by garvitraj** [comment]
Can i too work on this issue i would try to better design as per my graphic designing and UI/UX skills?
@swapnilsparsh pls assign this issue to me or i can collab with @Tarun-Kamboj and we both can give a better look to it.
Thanks

**Comment by swapnilsparsh** [comment]
> Can i too work on this issue i would try to diliver a better design as per my graphic designing and UI/UX skills?
> @swapnilsparsh pls assign this issue to me or i can collab with @Tarun-Kamboj and we both can give a better look to it.
> Thanks

Can you share some desgin that you have made ?

**Comment by Tarun-Kamboj** [comment]
@swapnilsparsh Are these fine?
![Screenshot (209)](https://user-images.githubusercontent.com/56023742/111589961-8b5b1a80-87eb-11eb-91b7-114373f69ceb.png)

![Screenshot (208)](https://user-images.githubusercontent.com/56023742/111589875-6cf51f00-87eb-11eb-9bcd-77ebf1fea1bd.png)

**Comment by sakshikhachane** [comment]
> @swapnilsparsh, @sakshikhachane can you take a look at these and tell me whether these are fine or not?
> 
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/56023742/111746648-55ce3400-88b4-11eb-9c89-da138ee8fffe.png">	<img alt="" width="200px" src="https://user-images.githubusercontent.com/56023742/111746707-654d7d00-88b4-11eb-8d39-765300f7834c.PNG">
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/56023742/111746870-9c239300-88b4-11eb-8521-6a990031c8f2.png">	<img alt="" width="200px" src="https://user-images.githubusercontent.com/56023742/111746927-acd40900-88b4-11eb-8bf0-f0e783e70bd2.PNG">

It is looking good. Make a PR.

**Comment by Tarun-Kamboj** [comment]
> > @swapnilsparsh, @sakshikhachane can you take a look at these and tell me whether these are fine or not?
> 
> It is looking good. Make a PR.

Done.
