### ISSUE TITLE
Our website needs attractive logo

### ISSUE THREAD

**Issue by garvitraj** [swapnilsparsh/Rescue#168]
Hey @swapnilsparsh i would like to contribute to basically Ui/Ux and fronted part as i too have those skills i would firstly like to design a better and attractive logo for our Website .
It would be a pleasure if you assign this issue to me.
Thanks

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh i would like to contribute to basically Ui/Ux and fronted part as i too have those skills i would firstly like to design a better and attractive logo for our Website .
> It would be a pleasure if you assign this issue to me.
> Thanks

Share some desgin if possible.

**Comment by Tarun-Kamboj** [comment]
Yea, a logo would look much better. 
| ![Screenshot (210)](https://user-images.githubusercontent.com/56023742/111591408-6cf61e80-87ed-11eb-8f5d-052e5d12ede4.png) | ![Screenshot (211)](https://user-images.githubusercontent.com/56023742/111591424-71bad280-87ed-11eb-9f87-ce48ebdd888d.png) |
|---|---|

@garvitraj can you share some designs.

**Comment by mansijain980** [comment]
Can i work on this?

**Comment by garvitraj** [comment]
@swapnilsparsh will share it today

**Comment by garvitraj** [comment]
I m Sharing a design pls look into it.
any feed or suggestion pls tell me
![Rescue logo](https://user-images.githubusercontent.com/62978449/111623927-0aaf1500-8811-11eb-809f-34add6fde45c.png)

**Comment by garvitraj** [comment]
can adjust the shape as per the website
and will surely do some more designs by end of the day

**Comment by sakshikhachane** [comment]
@garvitraj Go ahead with the issue. Happy learning :)

**Comment by garvitraj** [comment]
@sakshikhachane any feedback about above one 
should we go with the red theme

**Comment by sakshikhachane** [comment]
> @sakshikhachane any feedback about above one
> should we go with the red theme

Yes, a red theme would be better.

**Comment by garvitraj** [comment]
ok @sakshikhachane will make some more then we can finalize

**Comment by sakshikhachane** [comment]
Any updates?

**Comment by coding-geek21** [comment]
I would like to work on this issue can you please assign me

**Comment by sakshikhachane** [comment]
> I would like to work on this issue can you please assign me

Get the PRs for issues 189 and 190 in `ready-to-merge` state then you can go ahead with this issue.

**Comment by garvitraj** [comment]
@sakshikhachane can i make a pr for the logo

**Comment by swapnilsparsh** [comment]
> @sakshikhachane can i make a pr for the logo

You said you will share some logos, after that we can finalize 
If so, then you can message me on discord or linkedin.

**Comment by garvitraj** [comment]
@swapnilsparsh sorry for the late reply i was busy with my ese at collages it just got over today so will be sending some samples by today

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh sorry for the late reply i was busy with my ese at collages it just got over today so will be sending some samples by today

Sure 👍🏼

**Comment by swapnilsparsh** [comment]
@garvitraj Any updates ?

**Comment by garvitraj** [comment]
@swapnilsparsh sorry for the late update 
here by attaching tow variation pls give ur valuable feedback
![Uploading Group 12.png…]()
![Uploading Group 11.png…]()

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh sorry for the late update
> here by attaching tow variation pls give ur valuable feedback

Not able to see the attachments.

**Comment by garvitraj** [comment]
![Rescue logo](https://user-images.githubusercontent.com/62978449/114275908-ed511d80-9a41-11eb-8b6a-ea0574e9bf02.png)
![Group 12](https://user-images.githubusercontent.com/62978449/114275914-f17d3b00-9a41-11eb-9668-98952a66b34d.png)
![Group 11](https://user-images.githubusercontent.com/62978449/114275922-f8a44900-9a41-11eb-80b7-3324c5bbcf1b.png)

sorry for the inconvenience here attaching again

**Comment by swapnilsparsh** [comment]
@garvitraj Designs which you have shared are pretty good but they are not good enough.
If posssible share some more designs and use some illustrations or vector art if possible and keep the colour combination according to the UX.

**Comment by subhangi2731** [comment]
can you assign me this issue?

**Comment by sakshikhachane** [comment]
@garvitraj Any updates?

**Comment by coding-geek21** [comment]
@sakshikhachane  I was asking for this issue long back Can you please assign me, I would finish it within 2 or 3 days

**Comment by garvitraj** [comment]
@sakshikhachane i left the work in the middle due to a serious health issue 
but now I m fine will give a good piece of logo just give me a day or two time

**Comment by sakshikhachane** [comment]
Hey @coding-geek21,
Go ahead with the issue.

**Comment by coding-geek21** [comment]
I'm Attaching some logos here please have a look on it @sakshikhachane @swapnilsparsh 
If the design is okay then you can say whether there should be a change in font, text color and background color
so that i can change accordingly 

![logo](https://user-images.githubusercontent.com/53329034/117339988-053f8400-aebe-11eb-91e2-f1fbf0837bb4.jpg)

![logo](https://user-images.githubusercontent.com/53329034/117339967-fd7fdf80-aebd-11eb-849b-de40f5804c73.png)

![06052021164151A](https://user-images.githubusercontent.com/53329034/117340018-0d97bf00-aebe-11eb-9fe5-4a99c81ff0de.png)

**Comment by coding-geek21** [comment]
I will make some more designs tomorrow

**Comment by coding-geek21** [comment]
![logo](https://user-images.githubusercontent.com/53329034/117402270-b9272a80-af23-11eb-9966-eaf8ea7c9036.jpg)

**Comment by swapnilsparsh** [comment]
@coding-geek21 All the logos which you have made are awesome.
The last logo you have sent is more precise and good as compared to other logos, so just use some decent font, and then the logo will be ready.

**Comment by coding-geek21** [comment]
> @coding-geek21 All the logos which you have made are awesome.
> The last logo you have sent is more precise and good as compared to other logos, so just use some decent font, and then the logo will be ready.

sure I will make changes to font and update here

**Comment by coding-geek21** [comment]
![color_logo_with_background](https://user-images.githubusercontent.com/53329034/117808063-0dab0c80-b27a-11eb-8a08-36c6db0a6377.png)

Is this font okay for this logo? @swapnilsparsh

**Comment by coding-geek21** [comment]
![image](https://user-images.githubusercontent.com/53329034/117812800-e1928a00-b27f-11eb-9a09-674261e601c8.png)

@swapnilsparsh Is this font okay for this logo ? if any changes needed please update me.

**Comment by swapnilsparsh** [comment]
@coding-geek21 It's fine.

**Comment by coding-geek21** [comment]
> @coding-geek21 It's fine.

Ok @swapnilsparsh I will make PR tomorrow thanks for the update
