### ISSUE TITLE
grammatical mistake 

### ISSUE THREAD

**Issue by VaibhavSharma24** [swapnilsparsh/Rescue#175]
**Describe the bug**

A grammatical mistake of fullstop in a statement in the footer on the home page .

**Possible solution**

i want you to assign me this issue and i will resolve it.

i would love to do this.

i am GSSOC'21 participant @swapnilsparsh @sakshikhachane

**Comment by manasivaraiya** [comment]
want you to assign me this issue and i will resolve it.

I would love to do this.

I am GSSOC'21 participant

**Comment by ambivert-sam** [comment]
Hey! @VaibhavSharma24 I'm participant of GSSoC'21 I would like to contribute to this issue 
can you please assign it to me

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue. @VaibhavSharma24  Could you please assign this to me?

**Comment by sakshikhachane** [comment]
Hey @VaibhavSharma24,
The grammatical mistake is being fixed in one of the issues. So, I am closing this issue.
Please look for different issues or open new relevant issues.
