### ISSUE TITLE
Resolving bugs like...

### ISSUE THREAD

**Issue by SUMEKAGARWAL** [swapnilsparsh/Rescue#178]
- In Women's Rights section, when we hover on the block, there is no action. Its responsive when we hover on the text instead. So, I will add that functionality. The same is active in the other section-"Women's Safety Laws".
- Drop down is at the left side instead of right or along the end. I will resolve it.
- While creating a new contact, its mandatory to enter the email-id. What if parents don't have mail. So it shouldn't be mandatory.
- Deleting of contact should include the titles as "YES" or "NO" according to the question...Q.)Are you sure you want to permanently remove named contact?
- There are some sentences which are not meaningful and grammatically  correct. would like to modify them as well.
All the stated issues will be modified!

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue ,Could you please assign me this issue? @SUMEKAGARWAL

**Comment by SUMEKAGARWAL** [comment]
Hi @simranbhalla3 !
I am also a participant like you and I am not assigned with the issue yet!
Hello @swapnilsparsh , looking forward to make some commits if assigned.

**Comment by SUMEKAGARWAL** [comment]
Hello @swapnilsparsh , looking forward to make some commits if assigned.

**Comment by sakshikhachane** [comment]
@SUMEKAGARWAL Go ahead with the issue. Happy learning:)

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane The work is done!
 Looking forward for any other changes that has to be changed and if not, request you to merge my PR.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh @sakshikhachane
Have a look on these changes. If something is not up to the mark, please update the change that have to be committed.
And if not, merge my PR.
