### ISSUE TITLE
Web page having details about various NGOs that help Women.

### ISSUE THREAD

**Issue by jainayush362** [swapnilsparsh/Rescue#179]
**Is your feature request related to a problem? Please describe.**
----
- In India, there are many NGOs that are helping women to fight for their rights by providing them legal justice and many other services as well. The problem is that women's don't have much information about such NGOs and that's why they feel helpless. 

**Describe the solution you'd like**
----
- Under the option "MORE" in navigation bar, adding a new web page link "NGOs for Women" that will includes details about various NGOs in India that help women. Details like Services offered, Contact, Address etc. will be there on web page for each NGO.

**Additional context**
----
- The new web page will be fully responsive with good design.

@swapnilsparsh  @sakshikhachane If you find it useful and related then please assign me this so that I can start working on it. Once implemented, I think this will help many women. I hope you will label it under GSSoc21 and assign me this.

**Comment by sakshikhachane** [comment]
@jainayush362 Go ahead with this issue :)

**Comment by jainayush362** [comment]
> @jainayush362 This is indeed a good idea. Go ahead with this issue :)

Thank you so much......I have started working on this.
