### ISSUE TITLE
Improve the Footer 

### ISSUE THREAD

**Issue by simranbhalla3** [swapnilsparsh/Rescue#180]
**Is your feature request related to a problem? Please describe.**
----
I think the footer of this website can be improved 

**Describe the solution you'd like**
----It can be  made better by adding css and javascript

Please assign me this issue so that i can work on it and make better changes

**Comment by sakshikhachane** [comment]
Hey @simranbhalla3,
The footer enhancement is almost completed by one of the contributors. 
Please look for more issues or create your own issues. Happy contributing:)
