### ISSUE TITLE
Improve the fonts and color scheme of the website 

### ISSUE THREAD

**Issue by simranbhalla3** [swapnilsparsh/Rescue#182]
I'd like to work on the Frontend bugs , and make the website for catch to the eye by using css and javascript.
Please assign me this issue under Gssoc label so that i can work on it

**Comment by niya210** [comment]
I would like to work on it, being  GSSOC'21 participant, could I be assigned with this issue?

**Comment by sakshikhachane** [comment]
> I'd like to work on the Frontend bugs , and make the website for catch to the eye by using css and javascript.
> Please assign me this issue under Gssoc label so that i can work on it

Can you please elaborate more like which bugs?
