### ISSUE TITLE
creating sign up and sign in using email

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#183]
I'm a GSSoC'21 participant i'm interested in working on this issue , Can you please assign this to me

**Comment by manasivaraiya** [comment]
I'd like to contribute to this.
I am a GSSOC'21 participant

**Comment by shreya9301** [comment]
I'm a GSSoc'21 participant and I'm really looking forward to work on this issue. @coding-geek21 Please assign it to me .

**Comment by sakshikhachane** [comment]
@coding-geek21 Go ahead with the issue. Happy learning:)

**Comment by siddharth-143** [comment]
I'm a GSSoC'21 participant i'm interested in working on this issue . Would you like to assign me
