### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by nikhilkotiya** [swapnilsparsh/Rescue#184]
**Is your feature request related to a problem? Please describe.**
----
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

I want to add a preloader for this project.
I am a gssoc'21 participant and want to contribute on this project.

- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by sakshikhachane** [comment]
Hey @nikhilkotiya,
The preloader is already added by one of the contributors.
Please look for different issues or create your own issues. Happy contributing:)

**Comment by nikhilkotiya** [comment]
@sakshikhachane  But preloader is not visible in all URL. Also,  the time of loading is less.
