### ISSUE TITLE
A clean footer with quick links

### ISSUE THREAD

**Issue by vidhishah03** [swapnilsparsh/Rescue#187]
I want to add a clean footer to the website that will contain some quick links for navigation as well as the social media handles if any. It will also contain a "contact us" section with a section to send quick emails to the developers. 

I am a GSSOC'21 participant, kindly assign me this issue.

The preview looks something like this

![image](https://user-images.githubusercontent.com/58200995/111906677-b6f23500-8a77-11eb-9b9e-5fa7129aa3fd.png)

**Comment by sakshikhachane** [comment]
@vidhishah03 The footer is already redesigned, PR of which `ready-to-merge`. 
Thanks for suggesting:)
 You can look for other issues or make your own issues and let us know your great ideas.
