### ISSUE TITLE
Sending the confirmation mail after registration of the user

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#190]
Hi @sakshikhachane I would like to work on this issue, please assign me

**Comment by manasivaraiya** [comment]
I'd like to contribute to this issue.
I am a GSSOC'21 participant. pls assign this to me

**Comment by sakshikhachane** [comment]
Hey @coding-geek21,
I can assign you this issue only when #191 will be `ready-to-merge`. So please wait for this.

**Comment by coding-geek21** [comment]
> Hey @coding-geek21,
> I can assign you this issue only when #191 will be `ready-to-merge`. So please wait for this.

Okay @sakshikhachane  I will wait 😊

**Comment by sakshikhachane** [comment]
Hey @manasivaraiya,
Please look for different issues or create your own issues. We would like to look forward to your ideas:)
If @coding-geek21 is not able to complete the issue by tomorrow, then this issue will be assigned to you.

**Comment by shreyanshi16** [comment]
Hey! I would like to work on this issue. Please assign me.

**Comment by manasivaraiya** [comment]
> Hey @manasivaraiya,
> Please look for different issues or create your own issues. We would like to look forward to your ideas:)
> If @coding-geek21 is not able to complete the issue by tomorrow, then this issue will be assigned to you.

Okay no problem
