### ISSUE TITLE
Fix Extra White space on Women Safety Rules

### ISSUE THREAD

**Issue by simranbhalla3** [swapnilsparsh/Rescue#193]
**Describe the bug**
----
There is extra White Space before the footer when the website is viewed in Galaxy Fold screen

![image](https://user-images.githubusercontent.com/73423545/112100662-76a3cb80-8bcb-11eb-971f-fb873ac48eaf.png)
 I am a Gssoc participant and would like to work on this issue, Please assign this to me @sakshikhachane  @swapnilsparsh

**Comment by swapnilsparsh** [comment]
No need of this issue.
