### ISSUE TITLE
Changing password functionality

### ISSUE THREAD

**Issue by somya51p** [swapnilsparsh/Rescue#197]
**Is your feature request related to a problem? Please describe.**
----
Sometimes after signing up user wants to change the password for security reasons.

**Describe the solution you'd like**
----
Changing passwords and viewing their profile option would be provided to users that will make the user's experience better.

**Describe alternatives you've considered**
----
Viewing and editing profiles as well as changing passwords.

_I am a GSSOC contributor and wish to contribute to this issue. Please assign me the same._

**Comment by swapnilsparsh** [comment]
@somya51p Go ahead with the issue.

**Comment by swapnilsparsh** [comment]
@somya51p Any updates ?

**Comment by coding-geek21** [comment]
can I work on this issue @swapnilsparsh ?

**Comment by somya51p** [comment]
@swapnilsparsh I have sent the PR, soon I will resolve the conflicts. I have already given much time from my end to at least get it merged.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I have sent the PR, soon I will resolve the conflicts. I have already given much time from my end to at least get it merged.

When I asked , you didn't reply so I thought you are not doing work on this issue so I assigned it to someone else who was willing to work on this issue.
Sorry for the inconvenience caused, look after some other issues that are there.
