### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by somya51p** [swapnilsparsh/Rescue#198]
A page where users can send a message to the admins regarding any issue they are facing in the website or in case of any emergency would increase the security in many ways, and also its additional functionality.

_I am a GSSOC contributor and wish to contribute to this issue. Please assign me the same._

**Comment by Naman-12911** [comment]
Hello I want to add a contact page please assign me this issue under GSSOC.

**Comment by sakshikhachane** [comment]
@swapnilsparsh Have a look at this issue.

**Comment by swapnilsparsh** [comment]
@somya51p Work on it.

**Comment by KajalSinghBAGHEL** [comment]
I am GSSOC 21 participant I am a beginner and would like to work on this issue and learn new things, please assign me.

**Comment by swapnilsparsh** [comment]
@somya51p Any updates ?

**Comment by coding-geek21** [comment]
Can I work on this issue ? I'm familiar with back-end

**Comment by swapnilsparsh** [comment]
@somya51p is still working on it so you have to wait @coding-geek21

**Comment by coding-geek21** [comment]
> @somya51p is still working on it so you have to wait @coding-geek21

sure @swapnilsparsh I will wait

**Comment by mansijain980** [comment]
@sakshikhachane @swapnilsparsh I would like to work on this issue . Please assign this to me.
Thanks.

**Comment by coding-geek21** [comment]
> @sakshikhachane @swapnilsparsh I would like to work on this issue . Please assign this to me.
> Thanks.

@mansijain980  I have already asked and waiting for this issue to be assigned as someone is working on this

**Comment by coding-geek21** [comment]
@sakshikhachane  @swapnilsparsh Can i work on this issue ? as still it is not resolved

**Comment by swapnilsparsh** [comment]
@somya51p Are you working on this issue?

**Comment by somya51p** [comment]
> @somya51p Are you working on this issue?

@swapnilsparsh i had already sent the PR. Please have a look.
