### ISSUE TITLE
Update the footer text, and also to edit the padding to make it look good.

### ISSUE THREAD

**Issue by Devesh225** [swapnilsparsh/Rescue#199]
**Describe the bug**
----
- The text is grammatically incorrect in the footer section of every page of the website and also the padding between the text and the links(Developers, Helpline No.) is not looking good enough.

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to any page of the website. 
  2. Navigate to footer section.
  3. Visualize the footer text and also the padding between the text and the links.

**Expected behavior**
-----
- The text should be grammatically correct, and also the padding should look good as it is an amazing website.

**Possible solution**
----
- I want to correct the text and also adjust the padding between the blocks of text and links to make it more good.

**Comment by Devesh225** [comment]
I want to work on this issue as a part of Gssoc' 21, can you kindly assign it to me? @swapnilsparsh :)

**Comment by sakshikhachane** [comment]
Hey @Devesh225,
The footer is already redesigned and is yet to be merged. Please look for another issue or create your own issues. We would like to see more ideas.
