### ISSUE TITLE
Make the Website Responsive

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#2]

**Comment by SuNiL-Chau** [comment]
Hi I would like to contribute towards this can I give it a shot?

**Comment by swapnilsparsh** [comment]
X

> Hi I would like to contribute towards this can I give it a shot?

Yes

**Comment by swapnilsparsh** [comment]
> Hi I would like to contribute towards this can I give it a shot?

Yes

**Comment by bhavesh1129** [comment]
I would also like to work on it!

**Comment by swapnilsparsh** [comment]
> I would also like to work on it!

Ok

**Comment by abhinav-huria** [comment]
I would also like to work on this.

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@abhinav-huria  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by himanshu007-creator** [comment]
sir, i would like to work on this project

**Comment by swapnilsparsh** [comment]
> sir, i would like to work on this project

Thank you for showing you interest in the project.
@himanshu007-creator  you have to wait for 2-3 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by Sloth-Panda** [comment]
Hello, can I work on this issue?

**Comment by swapnilsparsh** [comment]
> Hello, can I work on this issue?

Thank you for showing you interest in the project.
@Sloth-Panda  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience
