### ISSUE TITLE
Documentation of Women Helpline Numbers Section (Add the left out States)

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#20]

**Comment by smriti1313** [comment]
Hi, I would like to do this.

**Comment by bhavesh1129** [comment]
Hii, I would like to take this up!

**Comment by swapnilsparsh** [comment]
OK

**Comment by swapnilsparsh** [comment]
@smriti1313 
Patch 1 PR has been merged. 
There are more patches or should I close this issue ?

**Comment by smriti1313** [comment]
@swapnilsparsh There are not more patches and also searched I on net to find more helpline numbers but they were not from the official site so did not include them. You can close the issue. Thank you for helping me out.

**Comment by swapnilsparsh** [comment]
Issue has been resolved by @smriti1313
