### ISSUE TITLE
Modifying the UI for Helpline numbers page

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#200]
The font should be a normal one instead.
I would like to work on styling of the table too.
Replace some illustrations with newer ones.

**Comment by sakshikhachane** [comment]
@tanishq-arya The font is better I think. Can you share some designs you have thought of if possible?

**Comment by tanishq-arya** [comment]
Sure. I will share it by today.

**Comment by tanishq-arya** [comment]
![Screenshot (987)](https://user-images.githubusercontent.com/77333275/112466020-60446e00-8d8b-11eb-8d89-a08f116f8c66.png)
![Screenshot (988)](https://user-images.githubusercontent.com/77333275/112466030-620e3180-8d8b-11eb-9d08-4a0f8a214d19.png)


I have redesigned something like this. But I am unable to make changes for mobile view because of the css.

**Comment by sakshikhachane** [comment]
Hey @tanishq-arya,
Go ahead with the issue.
