### ISSUE TITLE
UI issue: Back to top button 

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#201]
**Describe the bug**
----
- A clear and concise description of what the bug is.
The button uses 2 images and it can be made more efficient.

**To Reproduce**
----
- Steps to reproduce the behavior:

**Expected behavior**
-----
- A clear and concise description of what you expected to happen.

**Possible solution**
----
- Describe the solution you thought of.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by sakshikhachane** [comment]
@tanishq-arya Go ahead with the issue. Happy learning:)

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/112360558-76edb500-8cf8-11eb-9529-df169af7f752.png)
I have made something like this

**Comment by sakshikhachane** [comment]
Looking good! Just increase the radius of the circle if possible and then make a PR.
