### ISSUE TITLE
Send an Emergency SmS along with email 

### ISSUE THREAD

**Issue by Ratnesh4193** [swapnilsparsh/Rescue#206]
**Is your feature request related to a problem? Please describe.**
----
- Sending an sms along with the emergency email .

**Describe the solution you'd like**
----
- Would like to add a script to send sms update in emegency.

**Comment by sakshikhachane** [comment]
@Ratnesh4193 Can you elaborate on this?

**Comment by Ratnesh4193** [comment]
@sakshikhachane Along with email we can store the phone contacts .
And when emergency button is clicked we can send an auto generated sms along with  email.
Also probability of a person connected to internet conection is lesser 
so Sms can serve the purpose in a better way.

**Comment by swapnilsparsh** [comment]
> @sakshikhachane Along with email we can store the phone contacts .
> And when emergency button is clicked we can send an auto generated sms along with email.
> Also probability of a person connected to internet conection is lesser
> so Sms can serve the purpose in a better way.

Its already there #6
