### ISSUE TITLE
Navbar with Logo instead of using Home Icon

### ISSUE THREAD

**Issue by prsndp** [swapnilsparsh/Rescue#208]
Hi, I'm a GSSoC'21 participant and I think we need to add a logo on the navbar right side instead of using the **home logo**. So project admins please let me know about this idea.

**Comment by swapnilsparsh** [comment]
> Hi, I'm a GSSoC'21 participant and I think we need to add a logo on the navbar right side instead of using the **home logo**. So project admins please let me know about this idea.

#168 It's already there.
