### ISSUE TITLE
[FEATURE] [GSSOC' 21] Adding google auth to the project

### ISSUE THREAD

**Issue by Aditya201551** [swapnilsparsh/Rescue#210]
**Is your feature request related to a problem? Please describe.**
----
- It would be great if users would have an option to have a one-tap log in with google as it is frustrating to fill lengthy signup forms and verify their email after manual signups. 

**Describe the solution you'd like**
----
- I would like to add a `log in with google` feature to this project with google's OAuth login API

**Describe alternatives you've considered**
----
- NA

**Additional context**
----
- NA.
@swapnilsparsh @sakshikhachane

**Comment by swapnilsparsh** [comment]
@Aditya201551 Work on it.
