### ISSUE TITLE
Adding a faq page 

### ISSUE THREAD

**Issue by VaibhavSharma24** [swapnilsparsh/Rescue#215]
i would like to add a FAQ page on this website which will let people clear their common doubts.

i want you to assign me this work and i will love to do it.

**Comment by swapnilsparsh** [comment]
> i would like to add a FAQ page on this website which will let people clear their common doubts.
> 
> i want you to assign me this work and i will love to do it.

What common doubts, can you explain ?

**Comment by VaibhavSharma24** [comment]
yeah some common doubts like : 

Q . What does emergency button do ?
Q . What is the aim of this website ?
Q . Is it free to register ?
Q . How can i save my emergency numbers ?
Q . Where can i share my personal problem ?

**Comment by swapnilsparsh** [comment]
@VaibhavSharma24  Work on it and add some more FAQ.

**Comment by Ankita297** [comment]
Can i work on this ?
@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@VaibhavSharma24 Any updates ?

**Comment by VaibhavSharma24** [comment]
@swapnilsparsh sorry for not updating you i was busy in my college  yeah the faq page is ready just some minor modifications are left i will keep updating you  !

**Comment by sakshikhachane** [comment]
@VaibhavSharma24 May I know how much time do you require?

**Comment by VaibhavSharma24** [comment]
@sakshikhachane sorry for taking soo much time i actually got stucked in between i will be finished within 2 days sry for the delay
