### ISSUE TITLE
bug in navbar

### ISSUE THREAD

**Issue by Muskan-creator** [swapnilsparsh/Rescue#217]
In home section there is no effect or animations on navbar so do not add any interactivity to user without clicking but when we move to other pages it gives a hover effect of color change but not looks good also the font size is not matching with website
![rescue](https://user-images.githubusercontent.com/59757988/112760099-76fcf600-9013-11eb-8ee0-b02ba79e845b.png)

----
- A clear and concise description of what the bug is.

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to homepage
  2. Click on navbar items,you can see there is no interactivity
  3. Moving to other pages like safety laws there is bug in emergency section which is not good looking gives a transparent white color.
  4. Also font size is wrong and more is bolder than other heading on navbar 

**Expected behavior**
-----
There should be hover effect in icons and also in dropdown menu and remove bug in emergency section.

**Possible solution**
----I can change completely the navbar of homepage ,adds interactivity ,changes font size and also color combination themes,responsiveness,adding some hovering effects,removes bug of emergency section 

**Screenshots**
----
![image](https://user-images.githubusercontent.com/59757988/112760499-cee82c80-9014-11eb-97aa-951a752f535a.png)

**Comment by Muskan-creator** [comment]
Please assign this issue to me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Muskan-creator Go ahead.
