### ISSUE TITLE
Add a webpage for women's rights activists as image gallery .

### ISSUE THREAD

**Issue by mansijain980** [swapnilsparsh/Rescue#220]
**Description
A webpage which is having an image gallery of women's rights activists like Malala Yousafzai , Ramabai Ranade etc . and a little description about each of them.

It will make the website readable and attractive .

**Comment by swapnilsparsh** [comment]
@mansijain980 Ok, work on it.

**Comment by mansijain980** [comment]
Yes sir , i had already started but it will take some time actually my exams r going on bt i will commit it as soon as possible.
Thanks

**Comment by sakshikhachane** [comment]
@mansijain980 Any updates?

**Comment by mansijain980** [comment]
@sakshikhachane Yes ma'am , work is on progress due to xams it is delayed bt now i m continuing it .
Will commit a PR soon.
Thanks

**Comment by mansijain980** [comment]
@sakshikhachane my family tested covid positive , please give me some time .
Please.

**Comment by sakshikhachane** [comment]
Hey @mansijain980,
Sorry to hear this. Take care of yourself and your family. You are already working on another 2 issues and I think it's been so long that you were assigned. So I have to unassign you. Sorry for this but you can focus on the other 2 issues.

**Comment by mansijain980** [comment]
@sakshikhachane maam it's almost done due to sudden medical issue , i can't able to work ....if possible please give me time till tuesday morning as from monday i will be back to work properly hopefully.
Please , accept my request .
Thanks.

**Comment by coding-geek21** [comment]
@sakshikhachane Can I work on this issue?

**Comment by sakshikhachane** [comment]
Hey @mansijain980,
Hope you are doing good. Sorry for this but it's past one month that you were assigned the issue and the rules are such that we can't let anyone work for any issue for more than 1-2 weeks. Still, we had given you nearly 1 month. 
So @coding-geek21 go ahead with the issue.
