### ISSUE TITLE
Making the Carousel Slideshow on home page dynamic with read more button

### ISSUE THREAD

**Issue by niksm7** [swapnilsparsh/Rescue#221]
**Is your feature request related to a problem? Please describe.**
----
- The main aim of the carousel slideshow on home page is to motivate women but why restrict only to showcasing some of brave women. Changing code again and again for adding slides is a very tedious task.

**Describe the solution you'd like**
----
-  It would be better to fetch the items from database and display them with a read more link directing the user to articles worth reading.

**Additional context**
----
- I'm an **GSSOC '21** Participant so can you please assign me to work on this enhancement.

**Comment by swapnilsparsh** [comment]
@niksm7 Go ahead.
