### ISSUE TITLE
Show password option in login page

### ISSUE THREAD

**Issue by niksm7** [swapnilsparsh/Rescue#222]
**Is your feature request related to a problem? Please describe.**
----
- It is very frustrating to not know what password you are typing and get it wrong again and again.

**Describe the solution you'd like**
----
- It is better to keep a show password small button (eye shaped) so that anytime the user can view the password they are typing.

**Additional context**
----
- I'm a GSSOC '21 participant and want to work on this enhancement so can you please assign me the same.

**Comment by nitinshukla413** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by swapnilsparsh** [comment]
@niksm7 Work on it.
