### ISSUE TITLE
Dynamic Username and Email check for register form

### ISSUE THREAD

**Issue by niksm7** [swapnilsparsh/Rescue#226]
**Is your feature request related to a problem? Please describe.**
----
The register form expects username and email which should be unique according to Django authentication but when some other user tries to register with already existing username or email they are given an error "password mismatch" even though the passwords are same.

**Describe the solution you'd like**
----
It is better to check the username and email dynamically from the backend database while the user is giving the input so that even the user experience is maintained and there are less errors.

**Additional context**
----
I'm an GSSOC '21 participant and would like to work on these issues so I would request you to please assign me the same.

**Comment by swapnilsparsh** [comment]
@niksm7 Work on it.
More than one person can keep the same password so it's not necessary to make the password unique.
Make the username and email unique and if someone authenticate through google alos then keep in mind that email should be unique.

**Comment by swapnilsparsh** [comment]
@niksm7 Any updates ?

**Comment by niksm7** [comment]
Working on it will update you soon.
