### ISSUE TITLE
Add a user manual to the website

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#227]
### Adding a user manual will help the users understand the flow of the website and working of the website

I would like to work on this issue can you please assign me @swapnilsparsh @sakshikhachane

**Comment by swapnilsparsh** [comment]
> ### Adding a user manual will help the users understand the flow of the website and working of the website
> I would like to work on this issue can you please assign me @swapnilsparsh @sakshikhachane

Can you explain what type of user manual or any website which is having a user manual ?

**Comment by coding-geek21** [comment]
![image](https://user-images.githubusercontent.com/53329034/113534568-b9fc3200-95ee-11eb-8b37-660e5922822e.png)
We can have it like this in our home page 
or we can even create a separate like this  https://summerofcode.withgoogle.com/how-it-works/
here we can create a detailed explanation https://prod-cdn.preprod.co-vin.in/assets/pdf/user-guide-citizen-registration-ver-1.2.pdf  like this which is available in cowin website on clicking know how to book our appoinment
![image](https://user-images.githubusercontent.com/53329034/113539887-6b559480-95fc-11eb-9013-bdb09eaf63ed.png)


in our case we can give detailed explanation of the working of emergency messages and calls how we can create contacts step by step

**Comment by swapnilsparsh** [comment]
@coding-geek21 
Ok, work on it.

**Comment by swapnilsparsh** [comment]
@coding-geek21 Any updates ?

**Comment by coding-geek21** [comment]
Yes half completed I will make PR tomorrow
