### ISSUE TITLE
Addition of a webpage to help women Share their Stories

### ISSUE THREAD

**Issue by anushka1309paul** [swapnilsparsh/Rescue#229]
The website could be made more accessible and would seem more thoughtful and sensitive if a feature was added that would help women share their abuse stories and help other women reach out to them for support or share their stories as well. This would ensure that more number of women speak out against their abusers and be served justice. The page would contain articles for the same and a way for other women to comment on them to help those in distress. I would like to work on this issue if it is approved.

**Comment by swapnilsparsh** [comment]
> The website could be made more accessible and would seem more thoughtful and sensitive if a feature was added that would help women share their abuse stories and help other women reach out to them for support or share their stories as well. This would ensure that more number of women speak out against their abusers and be served justice. The page would contain articles for the same and a way for other women to comment on them to help those in distress. I would like to work on this issue if it is approved.

Great idea but currently there is no need of this feature.
