### ISSUE TITLE
Safety Manual Page

### ISSUE THREAD

**Issue by anushka1309paul** [swapnilsparsh/Rescue#230]
As a precautionary measure, the home page can have regular pop ups of random safety tips for women to be followed on road, public places, homes etc. and a separate page for safety tips as well as a self-defense manual for emergencies could make this website more useful and handy. I would like to work on this issue if it is approved.

**Comment by swapnilsparsh** [comment]
> As a precautionary measure, the home page can have regular pop ups of random safety tips for women to be followed on road, public places, homes etc. and a separate page for safety tips as well as a self-defense manual for emergencies could make this website more useful and handy. I would like to work on this issue if it is approved.

Work on safety manual page only.

**Comment by swapnilsparsh** [comment]
@anushka1309paul Any updates ?

**Comment by anushka1309paul** [comment]
Sir,
I had been unable to complete the same due to my ongoing examinations, but
I will finish the same at the earliest.
Thanks and Regards,
Anushka Paul
