### ISSUE TITLE
Add google Captcha

### ISSUE THREAD

**Issue by 2001asjad** [swapnilsparsh/Rescue#232]
In the login page along with the username and password, we can add google captcha to it. This will make the login page more enhanced and realistic. 
Can you please assign this issue to me. I am a GSSOC'21 participant. 
Thank You

**Comment by swapnilsparsh** [comment]
> In the login page along with the username and password, we can add google captcha to it. This will make the login page more enhanced and realistic.
> Can you please assign this issue to me. I am a GSSOC'21 participant.
> Thank You

Ok

**Comment by swapnilsparsh** [comment]
@2001asjad Any updates ?

**Comment by 2001asjad** [comment]
> @2001asjad Any updates ?

I was a bit preoccupied with my mid sems, gonna make a PR within tomorrow.

**Comment by coding-geek21** [comment]
@swapnilsparsh @sakshikhachane Can I work on this issue?
