### ISSUE TITLE
Location Details for SOS Sent to Nearest Police Station

### ISSUE THREAD

**Issue by khanfarhan10** [swapnilsparsh/Rescue#239]
- Broadcast Message to nearest located/prementioned Police Station

**Comment by iaryangoyal** [comment]
can i do this?

**Comment by sakshikhachane** [comment]
Sure! Go ahead @iaryangoyal.

**Comment by iaryangoyal** [comment]
Can U help me with some explanation what exactly I've to do

**Comment by khanfarhan10** [comment]
Like each user should provide the information (phone/email/landline) for the Police Station that is nearest to them.
If GPS is provided obtain the nearest Police Station using some API such as Google Maps.
After the data is obtained perform suitable actions.

**Comment by iaryangoyal** [comment]
#246

**Comment by farseenmanekhan1232** [comment]
Or we can use some kind of SMS API to send the SOS Location Details to the Nearest Police's Stations' Mobile Number or Something .

**Comment by farseenmanekhan1232** [comment]
To Obtain Nearest Police Stations' Mobile Number , we can Make use of Google Maps API .

**Comment by khanfarhan10** [comment]
@farseenmanekhan1232 Are you interested to work on this?

**Comment by farseenmanekhan1232** [comment]
I would love to 😊

**Comment by sakshikhachane** [comment]
Hey @farseenmanekhan1232,
Go ahead with the issue.
