### ISSUE TITLE
Fix register page for mobile view

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#248]
**Describe the bug**
----
- Font size and spacing have been modified and exceed screen width.

**To Reproduce**
----
- Steps to reproduce the behavior:

**Expected behavior**
-----
- A clear and concise description of what you expected to happen.

**Possible solution**
----
- Describe the solution you thought of.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.
- 
![Screenshot (1201)](https://user-images.githubusercontent.com/77333275/114356720-9147df80-9b8e-11eb-80c7-773685721192.png)
![Screenshot (1200)](https://user-images.githubusercontent.com/77333275/114356732-92790c80-9b8e-11eb-86dd-5c5ea190b25a.png)

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc

**Comment by swapnilsparsh** [comment]
<h1>It's working fine</h1>

![Annotation 2021-04-12 174906](https://user-images.githubusercontent.com/69387608/114393219-67ef7980-9bb7-11eb-8d32-0aec068011b6.png)
