### ISSUE TITLE
Add the motto of the website with typing text effect in home page

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#254]
@swapnilsparsh  I would like to work on this issue

**Comment by jatiinyadav** [comment]
Hey @coding-geek21, Can you provide a link or a hint about this effect?

**Comment by coding-geek21** [comment]
> Hey @coding-geek21, Can you provide a link or a hint about this effect?

yes here are some of text effect css animations
https://onaircode.com/html-css-text-typing-effect-examples/#:~:text=Typing%20Text%20Effect%20With%20CSS%20and%20HTML%20Only,they%20leave%20an%20enduring%20impact%20on%20the%20guest.

**Comment by coding-geek21** [comment]
May i know the reason??

**Comment by coding-geek21** [comment]
Or we can add just the motto alone without using any effects?? in home page, since there is less content at home page

**Comment by swapnilsparsh** [comment]
> Or we can add just the motto alone without using any effects?? in home page, since there is less content at home page

I will be opeing a new issue for home page as many things has to be change on home page.
