### ISSUE TITLE
Responsive navbar and improve it

### ISSUE THREAD

**Issue by Naman-12911** [swapnilsparsh/Rescue#264]
**Describe the bug**
when I open the website in the phone size the navbar is very small.
<img width="960" alt="2021-04-19" src="https://user-images.githubusercontent.com/66183578/115183697-ef7a4280-a0f9-11eb-9d2f-21eb91aff25e.png">
you can the navbar in the image it was very small.

I can improve it using css.

**Comment by swapnilsparsh** [comment]
@Naman-12911 
I will be opening a separate issue for the navbar and footer as they are very small, once the changes to home.html complete.
