### ISSUE TITLE
[GSSOC' 21] [FEATURE] Adding Facebook login to the app

### ISSUE THREAD

**Issue by Aditya201551** [swapnilsparsh/Rescue#266]
**Is your feature request related to a problem? Please describe.**
----
NA

**Describe the solution you'd like**
----
- Adding Facebook login to the app so users get a variety to login to the app

**Describe alternatives you've considered**
----
NA

**Additional context**
----
@swapnilsparsh I would like to work on this feature please assign me this issue

**Comment by sakshikhachane** [comment]
Hey @Aditya201551,
There is no need for this feature as of now. So, I am closing this issue.
