### ISSUE TITLE
Add github actions to auto-reply after successful pr merge

### ISSUE THREAD

**Issue by AB-san** [swapnilsparsh/Rescue#270]
Add github actions to greet the contributors after their pr is merged successfully 
For example -  thanks for contributing @username 
or any other lines as per the mentor's wish.

**Comment by AB-san** [comment]
I would like to work onthis issue

**Comment by sakshikhachane** [comment]
@AB-san Go ahead with the issue.

**Comment by AB-san** [comment]
> @AB-san Go ahead with the issue.

Hello @sakshikhachane I would like to know if this line  - "Thank you @username for your contribution. Looking forward for more such contribution"
