### ISSUE TITLE
Add a welcome bot 

### ISSUE THREAD

**Issue by Ankita297** [swapnilsparsh/Rescue#273]
**Is your feature request related to a problem? Please describe.**
----
A github action to greet contributor on opening his/her first PR or first issue  .

**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.
- 
![New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_52_56](https://user-images.githubusercontent.com/67833077/115980604-ac154d80-a5ab-11eb-8ef5-eeb849fbe0c5.png)

**Comment by sakshikhachane** [comment]
@Ankita297 Go ahead!
