### ISSUE TITLE
Found some html content in 404 error page

### ISSUE THREAD

**Issue by RuchiGitHu** [swapnilsparsh/Rescue#275]
**Describe the bug**
----
In the starting and end of the page, some extra content of html file is showing.

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to 'template'
  2. Click on '404'

**Expected behavior**
-----
There should not be HTML code written when we run the page.

**Possible solution**
----
I can remove those content. Please assign this issue to me @sakshikhachane.

**Screenshots**
----
![image](https://user-images.githubusercontent.com/71754179/115998872-05f73100-a607-11eb-9a36-dc968ead5744.png)
![image](https://user-images.githubusercontent.com/71754179/116111125-f8f44380-a6d3-11eb-84a3-37fa727a9d49.png)

**Comment by RuchiGitHu** [comment]
Please assign this issue to me @sakshikhachane

**Comment by sakshikhachane** [comment]
@RuchiGitHu There is no such error on my end. So, I am closing this issue.
