### ISSUE TITLE
Typo Error / Bug in Contributing file

### ISSUE THREAD

**Issue by akrish4** [swapnilsparsh/Rescue#28]
@swapnilsparsh  there is a typo error / bug in the contributing file , the  link to code of conduct file is redirected to some other's repository which  actually is a forked  repository of this project.
kindly assign me this issue 
the below shown is the image of contributing file 

![rescue_typo1](https://user-images.githubusercontent.com/61831021/103235052-22d86c00-4967-11eb-89d5-6a30567cbfb4.PNG)

and this is repo where it is redirected to when we click on code of conduct link 

![rescue_typo2](https://user-images.githubusercontent.com/61831021/103235119-4ef3ed00-4967-11eb-890b-24857c784d44.PNG)

**Comment by akrish4** [comment]
#29

**Comment by swapnilsparsh** [comment]
Issue resolved by @akrish4
