### ISSUE TITLE
Link 404 error page to the website

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#280]
**Is your feature request related to a problem? Please describe.**
----
The page for 404 error that is page not found is already made. Link this page to the website so that whenever the wrong URL will be entered, the 404 error page should be displayed.

**Comment by coding-geek21** [comment]
I would like to work on this issue please assign me @sakshikhachane

**Comment by sakshikhachane** [comment]
Go ahead with this issue! @coding-geek21
