### ISSUE TITLE
Register functionality is not working

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#284]
**Describe the bug**
----
- User is able to register through `Google account` but is unable to register using normal register functionality and is giving an alert as shown in the image.

![image](https://user-images.githubusercontent.com/53635792/116681268-62bd6780-a9ca-11eb-9b17-24a44f62e08d.png)

**Comment by mansijain980** [comment]
@sakshikhachane i would like to do work on this issue. Please assign this to me .
Thnks.

**Comment by coding-geek21** [comment]
I would like to work on this issue @sakshikhachane

**Comment by sakshikhachane** [comment]
Hey @mansijain980,
Go ahead with this issue.

**Comment by mansijain980** [comment]
![image](https://user-images.githubusercontent.com/63226239/117143265-45273e00-adce-11eb-9dd6-aa32be71f3c1.png)
this was missing in forms.py
But on running the server , before it was working right but now it is not .
Can u tell me why?

**Comment by sakshikhachane** [comment]
@mansijain980,
This is only the bug that we want to resolve.

**Comment by noblenihal** [comment]
@sakshikhachane Can I do this?
I think I have solved the issue

**Comment by swapnilsparsh** [comment]
@mansijain980 What is the update on your work?

**Comment by coding-geek21** [comment]
> I would like to work on this issue @sakshikhachane

I have asked for this issue previously so please assign me if the assignee is not able to resolve it

**Comment by mansijain980** [comment]
U can assign it to others as i m not well.
Thanks.

**Comment by coding-geek21** [comment]
> U can assign it to others as i m not well.
> Thanks.

Get well soon @mansijain980 , I will pray for you

**Comment by arpit456jain** [comment]
hey @coding-geek21 are you working on this issue ? 
can I give it a try ? @swapnilsparsh

**Comment by coding-geek21** [comment]
yes i'm working on it @arpit456jain
