### ISSUE TITLE
No Images in the website

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#293]
All the images that were there on the website are not showing due to some bug.
FIx it ASAP.

**Comment by swapnilsparsh** [comment]
@coding-geek21 If possible then please make the PR for this issue ASAP.

**Comment by arpit456jain** [comment]
its because DEBUG = False
 if DEBUG == True its working fine but then the 404 error can not be handled

**Comment by swapnilsparsh** [comment]
> its because DEBUG = False
> if DEBUG == True its working fine but then the 404 error can not be handled

In which file?

**Comment by arpit456jain** [comment]
> > its because DEBUG = False
> > if DEBUG == True its working fine but then the 404 error can not be handled
> 
> In which file?

Settings.py 

https://github.com/swapnilsparsh/Rescue/blob/master/mysite/settings.py

**Comment by coding-geek21** [comment]
@swapnilsparsh  I have made the PR and now this bug is fixed

**Comment by arpit456jain** [comment]
> @swapnilsparsh I have made the PR and now this bug is fixed

That's a really good fix . You handle the debug for both states (True and False) Great
