### ISSUE TITLE
Improve the Documentation of Women's Rights Section

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#3]

**Comment by akrish4** [comment]
i would like to work on this issue ( documentation of women's right and safety ) 
kindly assign me this 
and let me know where should i add the file , the exact path and it should be in a markdown file isnt it ? @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> i would like to work on this issue ( documentation of women's right and safety )
> kindly assign me this
> and let me know where should i add the file , the exact path and it should be in a markdown file isnt it ? @swapnilsparsh

You can make a separate branch and there you can do your work
Its not specific that you have to make it a markdown file, you can do it in any way you want.

**Comment by jatiinyadav** [comment]
Hii @swapnilsparsh , 
I would be glad if you assign me this issue.

**Comment by swapnilsparsh** [comment]
> Hii @swapnilsparsh ,
> I would be glad if you assign me this issue.

Yes you can work on this issue.

**Comment by smriti1313** [comment]
Hi, let me know if there is chance for me to contribute in this issue. Thank you

**Comment by swapnilsparsh** [comment]
@smriti1313 Ok

**Comment by musavveer** [comment]
Hey @swapnilsparsh I would like to work on this issue.
Can you give me a chance??

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh I would like to work on this issue.
> Can you give me a chance??

Thank you for showing you interest in the project.
@musavveer you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience

**Comment by musavveer** [comment]
> > Hey @swapnilsparsh I would like to work on this issue.
> > Can you give me a chance??
> 
> Thank you for showing you interest in the project.
> @musavveer you have to wait for 3-5 days as 2 people are already assigned on this issue.
> Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.
> 
> We appreciate your patience

Okay

**Comment by akrish4** [comment]
@swapnilsparsh  kindly check discord

**Comment by akrish4** [comment]
#11

**Comment by kanishkaa24** [comment]
Hello 
I would love to work on this issue.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@kanishkaa24 and @chehak123 you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by swapnilsparsh** [comment]
Issue resolved by @akrish4
