### ISSUE TITLE
UI : Improve the Header and Footer  

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#300]
**Is your feature request related to a problem? Please describe.**
----
I would like to improve the design and style of header and footer.

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
The footer is not consistent on all the pages.

**Describe the solution you'd like**
----
I would like to style the header and footer from scratch or use bootstrap for the same. I can implement any if you wish.  

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc

**Comment by swapnilsparsh** [comment]
@tanishq-arya There is no need to improve the Header and Footer, but if you want you can improve the UI of the whole website or few pages section-wise.
