### ISSUE TITLE
Sweet Alert before Log Out

### ISSUE THREAD

**Issue by arpit456jain** [swapnilsparsh/Rescue#305]
some times we click on logout by mistake so if there is confirmation modal it will be great and it will look cool also.
It will look like this
<img width="361" alt="alert" src="https://user-images.githubusercontent.com/55352601/118357472-ffb9fc00-b597-11eb-9698-a5d677b32d02.png">

**Comment by arpit456jain** [comment]
@swapnilsparsh can i make a PR for this

**Comment by swapnilsparsh** [comment]
@arpit456jain No need
