### ISSUE TITLE
Wave effect in footer

### ISSUE THREAD

**Issue by arpit456jain** [swapnilsparsh/Rescue#306]
i had added a Wave effect in footer i would like to make a PR for this

https://user-images.githubusercontent.com/55352601/118357881-db5f1f00-b599-11eb-8574-62a761fdd478.mp4

**Comment by arpit456jain** [comment]
@swapnilsparsh @sakshikhachane can i make a PR for this

**Comment by swapnilsparsh** [comment]
@arpit456jain No need for a wave effect.
