### ISSUE TITLE
Change the UI of carousel and make it responsive which is on the home page.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#32]

**Comment by patel-atul** [comment]
Hey @swapnilsparsh can i work on it please assign this to me.

**Comment by swapnilsparsh** [comment]
Ok @patel-atul

**Comment by patel-atul** [comment]
Can i improve other things too or only make carousal responsive

**Comment by swapnilsparsh** [comment]
@patel-atul Make the carousel responsive only.

**Comment by swapnilsparsh** [comment]
> Can i improve other things too or only make carousal responsive

Make the carousel responsive and change the UI also.
I am changing the name and level of this issue.

**Comment by sourav-coder** [comment]
@swapnilsparsh  Please assign this to me and check my PR.

**Comment by Sloth-Panda** [comment]
Hey, can you please give me this issue to work on?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Please assign this to me and check my PR.

Ok

**Comment by swapnilsparsh** [comment]
> Hey, can you please give me this issue to work on?

Thank you for showing you interest in the project.
@Sloth-Panda  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience

**Comment by swapnilsparsh** [comment]
Issue resolved by @sourav-coder
