### ISSUE TITLE
fix the alert box for deletion of emergency contact 

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#323]
![image](https://user-images.githubusercontent.com/53329034/118848597-86e6d700-b8ec-11eb-9d6b-b16191d8c255.png)

Alert box gets distorted on small screens I would like to work on this, please assign me

**Comment by tanishq-arya** [comment]
@swapnilsparsh can I work on this @coding-geek21 is fine with it as you 5 issues assigned at one time.

**Comment by coding-geek21** [comment]
> @swapnilsparsh can I work on this @coding-geek21 is fine with it as you 5 issues assigned at one time.

@swapnilsparsh  Please don't unassign me 😢 because it's not easy to find issues and i have also worked on it and created a Pull Request @tanishq-arya Everything is based on first come first serve basis only I opened this issue as I really want to work on this issue and I also made PRs for my previously created issues , And i was assigned only to 4 issues yesterday, If i'm not able to resolve this issue then you can kindly work on it

**Comment by tanishq-arya** [comment]
No issues. I was just saying if you're busy with other issues maybe I can work on this. All the best.
