### ISSUE TITLE
After registering redirect to another page showing confirmation mail sent

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#324]
After registering we have an alert saying a confirmation mail is sent to your email

![image](https://user-images.githubusercontent.com/53329034/118909680-ff778300-b940-11eb-86db-46b5db391c1a.png)

it would be better if we have it like this instead of alert we can redirect to another page showing like this

**Comment by swapnilsparsh** [comment]
@coding-geek21 Nice Idea 🤩
