### ISSUE TITLE
UI: Modifying the gallery page

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#325]
**Is your feature request related to a problem? Please describe.**
----
Adding a better card effect to the cards. Improving the overall appearance and modifying the font and illustration.

![image](https://user-images.githubusercontent.com/77333275/119133845-ff1edb00-ba59-11eb-9b39-e604e6750696.png)

**Comment by tanishq-arya** [comment]
@swapnilsparsh Please assign me this issue under gssoc.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Cards are perfect, you can just add a shadow and resize the photos so that they look the same in all sizes and resize the paragraphs in points so they don't look messy.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Please assign me this issue under gssoc.

@tanishq-arya Cards are perfect, you can just add a shadow and resize the photos so that they look the same in all sizes and resize the paragraphs in points so they don't look messy.
