### ISSUE TITLE
Bug in Password Reset Page

### ISSUE THREAD

**Issue by Saatvik21** [swapnilsparsh/Rescue#332]
**Describe the bug**
----
The page gets distorted below 594px. I would like to fix this issue

**To Reproduce**
----
- Steps to reproduce the behavior:

**Screenshots**
----
![Screenshot_2](https://user-images.githubusercontent.com/61618767/119236923-b8170f80-bb57-11eb-8104-bbd9345712bf.png)

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it. Windows 10

**Comment by swapnilsparsh** [comment]
@Saatvik21 Thank you for showing your interest in the project but the password page issue is assigned to @coding-geek21.
Look after some other issues.
