### ISSUE TITLE
UI: Adding illustrations on Rights, Laws and NGO page.

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#340]
**Is your feature request related to a problem? Please describe.**
Enhance the pages with illustrations, modify the font family to match other pages.

**Comment by tanishq-arya** [comment]
Please assign me this issue.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Can you mention with a proper screenshot where you will be adding illustrations on the page?

**Comment by tanishq-arya** [comment]
I'll do that.

**Comment by tanishq-arya** [comment]
@swapnilsparsh  I would like to update all these illustrations matching the theme and font.
![Screenshot (1799)](https://user-images.githubusercontent.com/77333275/120060241-46b5f000-c074-11eb-94f5-4b84ca26b05c.png)
![Screenshot (1798)_LI](https://user-images.githubusercontent.com/77333275/120060239-44ec2c80-c074-11eb-83d8-ae94522020eb.jpg)

**Comment by tanishq-arya** [comment]
Also style the button on these 3 pages.

**Comment by tanishq-arya** [comment]
@swapnilsparsh should I start working on this ?

**Comment by swapnilsparsh** [comment]
The heading which is there is good so no need of updating it.
