### ISSUE TITLE
Error at python manage.py migrate and python runserver

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#345]
![ss](https://user-images.githubusercontent.com/69387608/119718691-81a60100-be85-11eb-9ed7-6bf1a53bcbae.png)

**Comment by tanishq-arya** [comment]
Problem in views and URL


 send_mail(  # noqa            message_name,  # subject            message,  # message            message_email,  # from email            ["rescue@gmail.com"],  # To Email        )

**Comment by tanishq-arya** [comment]
I have made the changes should I make a PR ? @swapnilsparsh
