### ISSUE TITLE
Add a remember me option in login page

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#349]
**Is your feature request related to a problem? Please describe.**
----
-Sometimes it becomes hectic to type username and password often to login so we can have remember me option which saves the login information for particular period , this enables user to login easily 

**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by vinayak3010** [comment]
Sir I am a django developer and currently working on integrating my django backend to react frontend using REST Framework and trying to build REST APIs

**Comment by vinayak3010** [comment]
you may also refer to my repos which I have recently made

**Comment by vinayak3010** [comment]
They are on django and flask

**Comment by swapnilsparsh** [comment]
@vinayak3010 Inactive issue and not part of girlscript summer of code 2024

**Comment by vinayak3010** [comment]
Sir then assign me a different issue
