### ISSUE TITLE
Fix the css in django admin page

### ISSUE THREAD

**Issue by coding-geek21** [swapnilsparsh/Rescue#350]
**Describe the bug**
----
- Our django admin page looks improper without css , 

I would like to work on this, please assign me @swapnilsparsh 

**To Reproduce**
----
- Steps to reproduce the behavior:

**Expected behavior**
-----
- A clear and concise description of what you expected to happen.

**Possible solution**
----
- Describe the solution you thought of.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by mansijain980** [comment]
@swapnilsparsh i would like to work on it if @coding-geek21 is not working.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh i would like to work on it if @coding-geek21 is not working.

If you want you can work on it but you will not get any points in GSSOC as the program has been over.

**Comment by vinayak3010** [comment]
please assign me this issue

**Comment by vinayak3010** [comment]
Sir is there any issue open, upon which I may work on
