### ISSUE TITLE
footer fonts and hover

### ISSUE THREAD

**Issue by mansijain980** [swapnilsparsh/Rescue#352]
**contact us** and **contribute here**  should have same fonts size  as  **developers**  is having and when we hover to contact us and contribute here they both should expand a little like "developers" do.
- 
![image](https://user-images.githubusercontent.com/63226239/120029550-e42d0780-c013-11eb-9ecb-4b2d2dc4e718.png)

**Comment by swapnilsparsh** [comment]
NO need
