### ISSUE TITLE
Heading in mobile view

### ISSUE THREAD

**Issue by tanishq-arya** [swapnilsparsh/Rescue#357]
The headings move to left in mobile view.
![image](https://user-images.githubusercontent.com/77333275/120093263-b55b8200-c136-11eb-87ee-94af5019ee32.png)

**Comment by tanishq-arya** [comment]
@swapnilsparsh please assign me this issue.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Issues which you have mentioned here, kindly fix it in #186 as you only are working on it.

**Comment by tanishq-arya** [comment]
Okay I'll do that.
