### ISSUE TITLE
Make the Navbar Responsive

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#36]

**Comment by sakshikhachane** [comment]
@swapnilsparsh I would like to work on this issue. Can you please assign me this issue?

**Comment by swapnilsparsh** [comment]
Ok @sakshikhachane

**Comment by sakshikhachane** [comment]
@swapnilsparsh I have some suggestions.
Can we make the whole contents of the navbar except home shift to right? Also if we give the same color to it then it will look better. Should I try designing using my idea or should I modify your design only?

**Comment by swapnilsparsh** [comment]
@sakshikhachane You can design according to your comfort.

**Comment by sakshikhachane** [comment]
@swapnilsparsh Okay. Can you assign me this issue? So that I can proceed to do work.

**Comment by Swapnil-Gaur** [comment]
Hey @swapnilsparsh can I also work on this issue?

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh can I also work on this issue?

Ok

**Comment by Sloth-Panda** [comment]
Hey, can I please take the same issue?

**Comment by swapnilsparsh** [comment]
> Hey, can I please take the same issue?

Thank you for showing you interest in the project.
@Sloth-Panda  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience

**Comment by Swapnil-Gaur** [comment]
@swapnilsparsh where should I show navbar that I prepared?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh where should I show navbar that I prepared?

Share the Screenshot here

**Comment by Swapnil-Gaur** [comment]
It's  has animation effect

**Comment by Swapnil-Gaur** [comment]
(https://drive.google.com/file/d/1GEL_38Wm2BUa2CAXCDRW85B1NFfS7H5p/view?usp=drivesdk)
Please see its screenshot here.

**Comment by swapnilsparsh** [comment]
> (https://drive.google.com/file/d/1GEL_38Wm2BUa2CAXCDRW85B1NFfS7H5p/view?usp=drivesdk)
> Please see its screenshot here.

Attach the photo here only as I am unable to see on your drive as it is asking for permission.

**Comment by Swapnil-Gaur** [comment]
I am unable attach  photo here. Please once that Link now you can able to see

**Comment by swapnilsparsh** [comment]
> I am unable attach photo here. Please once that Link now you can able to see
I had seen your navbar its quite good but I want you to make the navbar as shown in the photo 
![image](https://user-images.githubusercontent.com/69387608/103476219-cbf4eb80-4dd9-11eb-9ce6-0c0f8b725d58.png)

**Comment by swapnilsparsh** [comment]
> I am unable attach photo here. Please once that Link now you can able to see

I had seen your navbar its quite good but I want you to make the navbar as shown in the photo
![image](https://user-images.githubusercontent.com/69387608/103476232-e5963300-4dd9-11eb-957e-cd5b4c43e436.png)

**Comment by Swapnil-Gaur** [comment]
Sure

**Comment by Swapnil-Gaur** [comment]
https://drive.google.com/file/d/1GXX5oV35TqOA7vRzbpLxBD0RtEoaqpRy/view?usp=drivesdk
@swapnilsparsh  i have done with this please check out once

**Comment by Swapnil-Gaur** [comment]
![20210104_110011](https://user-images.githubusercontent.com/71397235/103504100-6dcd1480-4e7c-11eb-8ac0-2494f0b5ff61.jpg)

**Comment by swapnilsparsh** [comment]
@Swapnil-Gaur Make a PR so that I can review your code.

**Comment by sakshikhachane** [comment]
@swapnilsparsh Is this better? Should I make a PR? Sorry for the delay.

![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_42](https://user-images.githubusercontent.com/53635792/103561085-e9f84400-4ede-11eb-8ba0-47ade2ad4bfa.png)
![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_37](https://user-images.githubusercontent.com/53635792/103561094-eebcf800-4ede-11eb-9182-ed830de6da3b.png)
![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_20](https://user-images.githubusercontent.com/53635792/103561098-efee2500-4ede-11eb-903b-3f33575d0c01.png)

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Is this better? Should I make a PR? Sorry for the delay.
> 
> ![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_42](https://user-images.githubusercontent.com/53635792/103561085-e9f84400-4ede-11eb-8ba0-47ade2ad4bfa.png)
> ![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_37](https://user-images.githubusercontent.com/53635792/103561094-eebcf800-4ede-11eb-9182-ed830de6da3b.png)
> ![127 0 0 1_8000_home_# - Google Chrome 04-01-2021 22_46_20](https://user-images.githubusercontent.com/53635792/103561098-efee2500-4ede-11eb-903b-3f33575d0c01.png)
> 
> 
> 

Yes it's looking great. 🤩

**Comment by swapnilsparsh** [comment]
@sakshikhachane Navbar is looking great 🤩

**Comment by Swapnil-Gaur** [comment]
@swapnilsparsh please review my PR.

**Comment by sakshikhachane** [comment]
@swapnilsparsh I have made a PR. Have a look at it :)

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh please review my PR.

You didn't made any PR.

**Comment by swapnilsparsh** [comment]
Issue resolved by @sakshikhachane
