### ISSUE TITLE
Error While Installing Dependencies [requirements.txt]

### ISSUE THREAD

**Issue by harshitbansall** [swapnilsparsh/Rescue#367]
**Describe the bug**
----
- Error While Installing Dependencies [requirements.txt]

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Create a virtual Environment
  2. Run command <code>pip install -r requirements.txt</code>

**Expected behavior**
-----
- Error should be returned, about installing <code>Microsoft Visual C++ 14.0 or greater</code>

**Possible solution**
----
- I think versions of the dependencies should be updated.

**Screenshots**
----
![Screenshot (66)](https://user-images.githubusercontent.com/24206423/156238622-7049de8f-997d-4525-8388-6c36802ae8d9.png)

**Comment by swapnilsparsh** [comment]
@harshitbansall Go ahead 👍🏻

**Comment by LokeshKumarES** [comment]
Python Version: 3.8.0

Django==3.0.6
django-allauth==0.50.0

will solve this your problem I am attaching new requirements.txt file 'requirements_new.txt'. 
[requirements_new.txt](https://github.com/user-attachments/files/17355864/requirements_new.txt)

**Comment by swapnilsparsh** [comment]
> Python Version: 3.8.0
> 
> Django==3.0.6 django-allauth==0.50.0
> 
> I hope this will solve your problem, I am attaching new requirements.txt file 'requirements_new.txt'. [requirements_new.txt](https://github.com/user-attachments/files/17355864/requirements_new.txt)

Thank you for resolving this, can you create the PR for the same attaching working screenshot of the project.
