### ISSUE TITLE
Improving update contact option

### ISSUE THREAD

**Issue by djm-1** [swapnilsparsh/Rescue#39]
The update contact field doesn't show the data in the corresponding fields. It pops up like a add contact form. I want to show the data on existing fields as well. User may want to update a specific field.

**Comment by swapnilsparsh** [comment]
> The update contact field doesn't show the data in the corresponding fields. It pops up like a add contact form. I want to show the data on existing fields as well. User may want to update a specific field.

Ok

**Comment by djm-1** [comment]
I have modified that. Please check my PR.
One more thing, 
/emergency_contact/ is showing all the saved contacts, but /emergency/ is not showing any at first. I think it's another bug. Can you please assign that task also? Should I create an issue?

**Comment by swapnilsparsh** [comment]
> I have modified that. Please check my PR.
> One more thing,
> /emergency_contact/ is showing all the saved contacts, but /emergency/ is not showing any at first. I think it's another bug. Can you please assign that task also? Should I create an issue?

Yes create another issue

**Comment by swapnilsparsh** [comment]
Issu resolved by @djm-1
