### ISSUE TITLE
Improve the Documentation of Women's Safety Laws Section

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#4]

**Comment by Harsh-bartariya** [comment]
I  would like to work on this issue sir
Please assign it to me sir @swapnilsparsh 
recently i attend sessions on women's safety by DSC WOW so it will be good for me to contribute something here.
thank you sir

**Comment by swapnilsparsh** [comment]
> I would like to work on this issue sir
> Please assign it to me sir @swapnilsparsh
> recently i attend sessions on women's safety by DSC WOW so it will be good for me to contribute something here.
> thank you sir

That great that you attended DSC WOW sessions and you can work on this issue.

**Comment by Harsh-bartariya** [comment]
@swapnilsparsh thank you sir.
sir my one last query is how much time i have to contribute in this particular issue i mean there will be some time limit for a assigned person to contribute in that limited period of time.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh thank you sir.
> sir my one last query is how much time i have to contribute in this particular issue i mean there will be some time limit for a assigned person to contribute in that limited period of time.

There is no time limit for anyone.

**Comment by jatiinyadav** [comment]
Hii @swapnilsparsh, 
I would be glad if you assign me this issue.

**Comment by swapnilsparsh** [comment]
> Hii @swapnilsparsh,
> I would be glad if you assign me this issue.

Yes you can work on this issue.

**Comment by smriti1313** [comment]
Hi, kindly let me know if I can work on this. I am eager to contribute in this project.

**Comment by IshetaBansal** [comment]
Hi !
Quite eager to work on this issue. Do let me know if I may. Thank you:)

**Comment by Pranjal-2001** [comment]
Hey! I am really interested to work on this issue. I would be glad to work on it!

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@smriti1313 , @IshetaBansal and @Pranjal-2001  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience

**Comment by kanishkaa24** [comment]
Hello 
I would love to work on this issue.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@kanishkaa24 and @chehak123 you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by swapnilsparsh** [comment]
One assignee role is left for this issue of you want to work on this issue then comment down below on the basis of first come first serve.

**Comment by jatiinyadav** [comment]
Heyy @swapnilsparsh , 
I would be glad if you assign me this issue.

**Comment by Akshu-on-github** [comment]
May I work on this?

**Comment by Sloth-Panda** [comment]
Hey, may I work on this?? plz let me know.

**Comment by jatinjain001** [comment]
I want to work on this issue Please assign it to me.

**Comment by swapnilsparsh** [comment]
> May I work on this?

Ok

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@Sloth-Panda and @jatinjain001  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by Akshu-on-github** [comment]
Just to clarify, I need to work on women_laws.html right? I plan to do the following:

- Make the description of the laws more concise
- Fact check the dates and acts
- Reorder the list (reverse chronological order) for greater relevance
- Add onto the list, if I find an important law missing

Please tell me if there is anything else I should do, or if there's anything that I should avoid doing.

**Comment by swapnilsparsh** [comment]
> Just to clarify, I need to work on women_laws.html right? I plan to do the following:
> 
> * Make the description of the laws more concise
> * Fact check the dates and acts
> * Reorder the list (reverse chronological order) for greater relevance
> * Add onto the list, if I find an important law missing
> 
> Please tell me if there is anything else I should do, or if there's anything that I should avoid doing.

Do this first then I will tell you if any changes have to be made.

**Comment by Sloth-Panda** [comment]
@swapnilsparsh  I can take this too

**Comment by swapnilsparsh** [comment]
#
