### ISSUE TITLE
Add Contributors.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [swapnilsparsh/Rescue#43]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by swapnilsparsh** [comment]
> Hai,
> I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

Ok

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it

**Comment by swapnilsparsh** [comment]
> I have created a pull request. Kindly review it

Mention me , Utkarsh mall, Utkarsh sharma the project admin and remove the img bot from contributors

**Comment by muthuannamalai12** [comment]
Ok.I will do it

**Comment by muthuannamalai12** [comment]
I have changed it. Kindly review it

**Comment by swapnilsparsh** [comment]
Issue resolved by @muthuannamalai12
