### ISSUE TITLE
On clicking emergency contact error is showing 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#44]
![Annotation 2021-01-02 235003](https://user-images.githubusercontent.com/69387608/103463820-4a5b7a00-4d55-11eb-8b2a-caeb28591111.png)

**Comment by djm-1** [comment]
It's not a bug. I think you didn't run migrations.
python manage.py makemigrations 
python manage.py migrate 
should solve this.

**Comment by swapnilsparsh** [comment]
> I think you didn't run migrations.
> python manage.py makemigrations
> python manage.py migrate
> should solve this.

Thank You.
It worked.
