### ISSUE TITLE
On home page when clicking on more than dropdown menu is not opening

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#47]

**Comment by Amit366** [comment]
Can I try to solve this issue??

**Comment by Amit366** [comment]
On clicking the home icon what icons should drop down?

**Comment by swapnilsparsh** [comment]
> On clicking the home icon what icons should drop down?

It is not working on homepage only other than its working fine.
You can have a look at other page then open the dropdown , you will get the idea.

**Comment by Amit366** [comment]
Fill the details in
main_app/mail.py

this is showing error as 'main_app' is not recognized as an internal or external command,
operable program or batch file.

**Comment by swapnilsparsh** [comment]
> Fill the details in
> main_app/mail.py
> 
> this is showing error as 'main_app' is not recognized as an internal or external command,
> operable program or batch file.

Fix this issue and make a PR

**Comment by Amit366** [comment]
Sir could you please help me in fixing this issue

**Comment by swapnilsparsh** [comment]
> Sir could you please help me in fixing this issue

Yes

**Comment by Amit366** [comment]
Sir on typing "main_app/mail.py" I am getting an error:
"this is showing error as 'main_app' is not recognized as an internal or external command,
operable program or batch file."

Could u please help me in fixing this.

**Comment by swapnilsparsh** [comment]
This issue has been resolved.
