### ISSUE TITLE
Show the contributors name on README.md file

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#48]
Show the CONTRIBUTORS.md table on README.md or make a new table.
For [reference](https://github.com/swapnilsparsh/Unified-Codes/blob/master/README.md) you can have a look.

**Comment by jatiinyadav** [comment]
Heyy @swapnilsparsh ,
I would be glad if you assign me this issue

**Comment by Akshu-on-github** [comment]
May I work on this issue?

**Comment by jatinjain001** [comment]
May I work on this issue ??

**Comment by swapnilsparsh** [comment]
> May I work on this issue ??

Thank you for showing you interest in the project.
@jatinjain001  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by Akshu-on-github** [comment]
Please take a look at PR #53

**Comment by swapnilsparsh** [comment]
> Please take a look at PR #53

Move the table under the Contributors heading and don't add too much emoji.

**Comment by Akshu-on-github** [comment]
> don't add too much emoji

What would you like me to remove?

**Comment by swapnilsparsh** [comment]
> > don't add too much emoji
> 
> What would you like me to remove?

Limit the usage of emoji under my name that you have used 4 emoji.
Reduce it to 2

**Comment by Akshu-on-github** [comment]
> > > don't add too much emoji
> > 
> > 
> > What would you like me to remove?
> 
> Limit the usage of emoji under my name where you have used 4 emoji.
> Reduce it to 2

The mentor role was a combination of two emojis in the emoji key, I have removed the same. Take a look now?

**Comment by swapnilsparsh** [comment]
> > > > don't add too much emoji
> > > 
> > > 
> > > What would you like me to remove?
> > 
> > 
> > Limit the usage of emoji under my name where you have used 4 emoji.
> > Reduce it to 2
> 
> The mentor role was a combination of two emojis in the emoji key, I have removed the same. Take a look now?

Issue has been resolved by @Akshu-on-github
