### ISSUE TITLE
Improve the Documentation of Women Helpline Numbers Section

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#5]

**Comment by akrish4** [comment]
i would like to work on this issue too @swapnilsparsh 
let me know more details about the documentation on markdown ?

**Comment by swapnilsparsh** [comment]
> i would like to work on this issue too @swapnilsparsh
> kindly assign me this issue
> let me know more details about the documentation on markdown ?

You have to make the doucmentation more efficient and to the point.

**Comment by jatiinyadav** [comment]
Hii @swapnilsparsh, 
I would be glad if you assign me this issue.

**Comment by swapnilsparsh** [comment]
> Hii @swapnilsparsh,
> I would be glad if you assign me this issue.

Yes you can work on this issue.

**Comment by smriti1313** [comment]
Hi, I would like to contribute in this too. Kindly let me know if there's a chance of me getting included in this.

**Comment by swapnilsparsh** [comment]
> Hi, I would like to contribute in this too. Kindly let me know if there's a chance of me getting included in this.

Thank you for showing you interest in the project.
@smriti1313 you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by kanishkaa24** [comment]
Hello 
I would love to work on this issue.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by swapnilsparsh** [comment]
Thank you for showing you interest in the project.
@kanishkaa24 and @chehak123 you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by akrish4** [comment]
@swapnilsparsh kindly check discord

**Comment by akrish4** [comment]
#16

**Comment by swapnilsparsh** [comment]
Issue resolved  by @akrish4

**Comment by smriti1313** [comment]
@swapnilsparsh many states are still missing from the list.

**Comment by akrish4** [comment]
@smriti1313  
***only major states need to be added*** , said by the project maintainer/ owner

**Comment by swapnilsparsh** [comment]
> @smriti1313
> _**only major states need to be added**_ , said by the project maintainer/ owner

Let @smriti1313 work on other states as she also wants to contribute in the project.
Major edits has already been done by you @akrish4

**Comment by akrish4** [comment]
@swapnilsparsh sure

**Comment by swapnilsparsh** [comment]
> > @smriti1313
> > _**only major states need to be added**_ , said by the project maintainer/ owner
> 
> Let @smriti1313 work on other states as she also wants to contribute in the project.
> Major edits has already been done by you @akrish4

@smriti1313 I will be openign a spearate issue for this, there you can ask for the assignee role and then you can start your work.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh sure

@smriti1313 I will be openign a spearate issue for this, there you can ask for the assignee role and then you can start your work.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh sure

@smriti1313 I will be opening a spearate issue for this, there you can ask for the assignee role and then you can start your work.

**Comment by smriti1313** [comment]
@

> 
> 
> > @swapnilsparsh sure
> 
> @smriti1313 I will be opening a spearate issue for this, there you can ask for the assignee role and then you can start your work.

okay thank you. I have actually done with this part. I am waiting when i can request a PR.

**Comment by swapnilsparsh** [comment]
> @
> 
> > > @swapnilsparsh sure
> > 
> > 
> > @smriti1313 I will be opening a spearate issue for this, there you can ask for the assignee role and then you can start your work.
> 
> okay thank you. I have actually done with this part. I am waiting when i can request a PR.

Refer to #20
