### ISSUE TITLE
Make the following pages responsive.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#51]
Make these page responsive -
1. helpline_numbers.html
2. women_laws.html
3. women_rights.html

**Comment by sakshikhachane** [comment]
@swapnilsparsh I would like to work on this issue. If it is first come first serve then can we split the work?

**Comment by swapnilsparsh** [comment]
@kritikashah20 and @sakshikhachane Ok

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I would like to work on this issue. If it is first come first serve then can we split the work?

You have to make all three pages responsive in order to resolve this issue as this is a level 5 issue.

**Comment by JandedAstro** [comment]
I would like to work on this issue too.

**Comment by swapnilsparsh** [comment]
> I would like to work on this issue too.

Thank you for showing you interest in the project.
@JandedAstro  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience

**Comment by sakshikhachane** [comment]
@swapnilsparsh Will, you please add some tasks for this?

**Comment by swapnilsparsh** [comment]
Thank you @sakshikhachane for pointing out that two pages are already responsive.
I am closing this issue and I will open another issue in which you can do the work accordingly.
