### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [swapnilsparsh/Rescue#52]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by swapnilsparsh** [comment]
> I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> For reference, check out: https://github.com/apps/welcome
> 
> If you feel this is a great idea!
> Please assign it to me.

Great idea.
You can start you work.

**Comment by musavveer** [comment]
@swapnilsparsh I would like to work on it.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I would like to work on it.

Ok

**Comment by muthuannamalai12** [comment]
> > I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> > For reference, check out: https://github.com/apps/welcome
> > If you feel this is a great idea!
> > Please assign it to me.
> 
> Great idea.
> You can start you work.

I have created a Pull Request. Kindly review it @swapnilsparsh

**Comment by swapnilsparsh** [comment]
Issue resolved by @muthuannamalai12
