### ISSUE TITLE
Issue and PR templates.

### ISSUE THREAD

**Issue by musavveer** [swapnilsparsh/Rescue#54]
Issue and PR templates are missing.
I can do it. Please assign this to me. @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> Issue and PR templates are missing.
> I can do it. Please assign this to me. @swapnilsparsh

Can you share some photos so I can get an idea what you are talking about.

**Comment by musavveer** [comment]
When someone opens an Issue or PR it asks for a checklist and some instructions.

**Comment by swapnilsparsh** [comment]
> When someone opens an Issue or PR it asks for a checklist and some instructions.

Can you share some example ?

**Comment by Sloth-Panda** [comment]
@swapnilsparsh  

issue template-> 
![Screenshot (50)](https://user-images.githubusercontent.com/70213384/104856827-a0761300-593a-11eb-8845-c7d6db067d77.png)
Issue template looks something like this it says what sort of issue someone is creating when he/she is creating an issue.

pr template->
![Screenshot (54)](https://user-images.githubusercontent.com/70213384/104856960-4c1f6300-593b-11eb-98df-f00cd9fd9fed.png)

Pr template looks something like this its bbasically conatins a set of checklist that the pr relates to and description of what sort of change was made in the pr

**Comment by Sloth-Panda** [comment]
Can i work  on this @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Sloth-Panda Ok

**Comment by swapnilsparsh** [comment]
Issue resollved by @Sloth-Panda
