### ISSUE TITLE
After logging in the dashboard's header does not have proper orientation

### ISSUE THREAD

**Issue by Sloth-Panda** [swapnilsparsh/Rescue#57]
![Screenshot (37)](https://user-images.githubusercontent.com/70213384/104084031-8d43b300-5269-11eb-82c5-c97111c7a059.png)

**Comment by Sloth-Panda** [comment]
Let me know if any work needs to be done on this. The logged-in name is pushed up  and the alignment of things are not perfect and also some part of the header is coming down a bit as you can see

**Comment by swapnilsparsh** [comment]
@Sloth-Panda I will assign the issue to you so that you can start your work.

**Comment by Sloth-Panda** [comment]
@swapnilsparsh check it out

**Comment by swapnilsparsh** [comment]
Issue resolved by @Sloth-Panda
