### ISSUE TITLE
This website is not  perfectly responsive a lot of bugs are there

### ISSUE THREAD

**Issue by Sloth-Panda** [swapnilsparsh/Rescue#59]
Hey, if you want to make it responsive let me know

**Comment by swapnilsparsh** [comment]
> Hey, if you want to make it responsive let me know

Can you attach a photo of the bugs that you have noticed.

**Comment by LazyCoder-1506** [comment]
i want to try this issue

**Comment by Sloth-Panda** [comment]
hey I am on it will be making  pr in few days

**Comment by Sloth-Panda** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/70213384/104557636-9a94df00-5667-11eb-9623-cbf6a78a88d1.png)

This is one

and also the font-sizes are not chaning its too big when someone views the site on phone
and also the image quality is dropping a lot the main "rescue" poster so that too can be corrected

**Comment by swapnilsparsh** [comment]
@Sloth-Panda Ok work on this issue.

**Comment by swapnilsparsh** [comment]
@Sloth-Panda You have opened the issue stating that there are lot of bugs and the website is also not responsive so I have added the Level 4 label so do the work accordingly.
