### ISSUE TITLE
The toggle button is not working fine

### ISSUE THREAD

**Issue by Sloth-Panda** [swapnilsparsh/Rescue#61]
toggle button is not toggling properly when I click on it its just goes up and the  again comes down

**Comment by swapnilsparsh** [comment]
> toggle button is not toggling properly when I click on it its just goes up and the again comes down

Share the photo

**Comment by LazyCoder-1506** [comment]
@Sloth-Panda  please elaboarte the issue using photo, if i can i want to contribute
