### ISSUE TITLE
Issue with the landing page and other pages before logging in as user

### ISSUE THREAD

**Issue by Sloth-Panda** [swapnilsparsh/Rescue#62]
when someone directly hops into the margin page and after that opens-up other pages then some text are covered/not visible of the other pages 
![Screenshot (53)](https://user-images.githubusercontent.com/70213384/104842317-a5ac7100-58ec-11eb-913c-29bd504fb8b1.png)

Now you can see those top sections like "welcome" part is clearly visible and also corrected all other landing pages before the signup those were showing the same issue @swapnilsparsh

**Comment by Sloth-Panda** [comment]
@swapnilsparsh  checkout the pr and let me know

**Comment by swapnilsparsh** [comment]
@Sloth-Panda You dont have to open this issue as you have to do this task in issue #59
