### ISSUE TITLE
Fix the Navbar

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#69]
![127 0 0 1_8000_home__-_Google_Chrome_19-01-2021_16_32_17](https://user-images.githubusercontent.com/69387608/105026281-6315a080-5a74-11eb-851b-2df544211356.png)

While checking is it responsive or not there is a bug which you have to fix.

**Comment by sakshikhachane** [comment]
@swapnilsparsh I would like to work on this issue.

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by swapnilsparsh** [comment]
@sakshikhachane and @nehaparmar99 Ok

**Comment by nehaparmar99** [comment]
Hey!I'm done with the changes.Should I change the navbar on all the pages then?
