### ISSUE TITLE
Improve the Footer 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#7]

**Comment by patel-atul** [comment]
Can I work on this.

**Comment by bhavesh1129** [comment]
May I work on this!

**Comment by swapnilsparsh** [comment]
Yes, both of you can work on this issue.

**Comment by patel-atul** [comment]
hey @swapnilsparsh this site is using w3.css framework shoul i have to work with that or I can write my own css for styling.
also can i create a stylesheet for all the css

**Comment by swapnilsparsh** [comment]
@patel-atul You can work according to your comfort.

**Comment by kanishkaa24** [comment]
Hello 
I would love to work on this issue.

**Comment by patel-atul** [comment]
hey @swapnilsparsh I have created this footer can you look at it.
![footer rescue](https://user-images.githubusercontent.com/73336171/103167683-427e7000-4853-11eb-8014-049bea3c70a2.png)
I have also made it fully responsive without using any media queries.
![footer rescue 1](https://user-images.githubusercontent.com/73336171/103167688-5d50e480-4853-11eb-8479-1a46458244df.png)
![footer rescue 2](https://user-images.githubusercontent.com/73336171/103167690-5f1aa800-4853-11eb-94e7-9cb8b5f128f9.png)
But I am not able to add it in the website source code.
I have added all the html in home.html that worked on it and created style.css file for styles but they are not showing on page.
![footer rescue 3](https://user-images.githubusercontent.com/73336171/103167801-48c11c00-4854-11eb-9aa0-003f91c8d60c.png)
![footer rescue 4](https://user-images.githubusercontent.com/73336171/103167804-49f24900-4854-11eb-9738-3feaf0e76af2.png)

**Comment by patel-atul** [comment]
> hey @swapnilsparsh I have created this footer can you look at it.
> ![footer rescue](https://user-images.githubusercontent.com/73336171/103167683-427e7000-4853-11eb-8014-049bea3c70a2.png)
> I have also made it fully responsive without using any media queries.
> ![footer rescue 1](https://user-images.githubusercontent.com/73336171/103167688-5d50e480-4853-11eb-8479-1a46458244df.png)
> ![footer rescue 2](https://user-images.githubusercontent.com/73336171/103167690-5f1aa800-4853-11eb-94e7-9cb8b5f128f9.png)
> But I am not able to add it in the website source code.
> I have added all the html in home.html that worked on it and created style.css file for styles but they are not showing on page.
> ![footer rescue 3](https://user-images.githubusercontent.com/73336171/103167801-48c11c00-4854-11eb-9aa0-003f91c8d60c.png)
> ![footer rescue 4](https://user-images.githubusercontent.com/73336171/103167804-49f24900-4854-11eb-9738-3feaf0e76af2.png)

Can Anyone help me with this

**Comment by swapnilsparsh** [comment]
@patel-atul Footer is looking great.
You have to link the file in urls.py and views.py.

**Comment by patel-atul** [comment]
how exactly I can do that I am new at python and django.

**Comment by swapnilsparsh** [comment]
@patel-atul Footer which you have made is awesome.
You have to make just few changes,
1. Use the same font which is used in the website
2. Footer which you have made is only showing on home page, it should show on every page.

**Comment by jatinjain001** [comment]
I would like to work on this . Please let me know.

**Comment by swapnilsparsh** [comment]
> I would like to work on this . Please let me know.

Ok

**Comment by jatinjain001** [comment]
Thank you 😊

**Comment by jatinjain001** [comment]
Check my PR I did , and let me know if it is need to do more changes . thank you @swapnilsparsh

**Comment by swapnilsparsh** [comment]
Issue resolved by @jatinjain001
