### ISSUE TITLE
The pages start before the navbar, and hence the top content is cropped out.

### ISSUE THREAD

**Issue by nehaparmar99** [swapnilsparsh/Rescue#73]
**Describe the bug**
----
The content at the top is right now being overlapped with the navbar.

**Expected behavior**
-----
- The pages should begin from a little below from what they're now.

**Possible solution**
----
Setting the margin-top for the pages.
**Screenshots**
----
![Screenshot (267)](https://user-images.githubusercontent.com/48972593/105051768-18585080-5a95-11eb-9831-0a3bb20e8636.png)
![Screenshot (266)](https://user-images.githubusercontent.com/48972593/105051780-1db59b00-5a95-11eb-8202-567808c46295.png)

**Comment by nehaparmar99** [comment]
I'd like to make the changes

**Comment by swapnilsparsh** [comment]
@nehaparmar99 You have to fix all the pages where navbar is overlapping.

**Comment by nehaparmar99** [comment]
Sure👍🏻
