### ISSUE TITLE
Improving UI of login and sign up pages (Register and Login page)

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#75]
**Is your feature request related to a problem? Please describe.**
----
- The Ui is not pleasing and can be made better.

**Describe the solution you'd like**
----
- Make a better design of UI.

**Comment by swapnilsparsh** [comment]
@sakshikhachane Ok

**Comment by swapnilsparsh** [comment]
@sakshikhachane Specify the pages on which you will work.

**Comment by sakshikhachane** [comment]
I will be working on the register and login page.

**Comment by 07yuvraj** [comment]
I want to work on this.May I?

**Comment by 07yuvraj** [comment]
Is it closed or can i work on any other page??

**Comment by sakshikhachane** [comment]
@07yuvraj I have made PR for this and it is merged and I am working on other pages as well :)

**Comment by swapnilsparsh** [comment]
> Is it closed or can i work on any other page??

This issue is closed but you can work on other issues which are open.
