### ISSUE TITLE
FIx the footer 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#76]
<div align = "center">
<h2>On some pages footer is not working properly</h2>

![Annotation 2021-01-21 200958](https://user-images.githubusercontent.com/69387608/105365964-d231f700-5c24-11eb-9829-655e510518e9.png)
![Annotation 2021-01-21 201017](https://user-images.githubusercontent.com/69387608/105365972-d3632400-5c24-11eb-8516-f18f75f380fe.png)

<h2>On some pages its working fine so <br>you have to make the footer look like this on every page.</h2>

![FIX](https://user-images.githubusercontent.com/69387608/105366591-8895dc00-5c25-11eb-9646-a558fcd7716f.png)
</div>

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by jatiinyadav** [comment]
Hey @swapnilsparsh,
I would like to work on this issue
