### ISSUE TITLE
FIx the Emergency option

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#8]
When no contacts is saved then on clicking the Emergency option it should redirect you to Emergency Contacts page.

**Comment by SHAIMA-HAQUE** [comment]
Hi!
I would like to give this a shot .Could you please assign it to me?

**Comment by swapnilsparsh** [comment]
> Hi!
> I would like to give this a shot .Could you please assign it to me?

Ok

**Comment by SHAIMA-HAQUE** [comment]
Sir,Could you please guide me as to how I can reproduce the bug?

**Comment by swapnilsparsh** [comment]
> Sir,Could you please guide me as to how I can reproduce the bug?

When no contacts is saved then on clicking the Emergency option it should redirect you to Emergency Contacts page.

**Comment by musavveer** [comment]
Hi! I would like to work on this issue.
Please assign this to me.

**Comment by swapnilsparsh** [comment]
> Hi! I would like to work on this issue.
> Please assign this to me.

Ok @musavveer

**Comment by musavveer** [comment]
Thank You @swapnilsparsh 
See my DM on discord

**Comment by SubhradeepSS** [comment]
@swapnilsparsh Can u also assign me this issue to?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Can u also assign me this issue to?

Thank you for showing you interest in the project.
@SubhradeepSS  you have to wait for 3-5 days as 2 people are already assigned on this issue.
Kindly give some time to the assignees to resolve the issue then you can work on this issue till then look after some other issues.

We appreciate your patience.

**Comment by swapnilsparsh** [comment]
Issue has been resolved by @musavveer
