### ISSUE TITLE
Improving UI of women laws, women rights and helpline number pages

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#81]
**Is your feature request related to a problem? Please describe.**
----
Modifying the user interface of the three pages - women's laws, women's rights, and helpline number.

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me ,If it is available

**Comment by sakshikhachane** [comment]
Hi @jatinjain001 , I am already working on this issue and have completed two pages.

**Comment by jatinjain001** [comment]
> Hi @jatinjain001 , I am already working on this issue and have completed two pages.

I already told if it is available 😊😊

**Comment by jatinjain001** [comment]
I am  working on it

**Comment by jatinjain001** [comment]
Changed the UI of helpline numbers, I am bit confused regarding laws and right page . In my view there should be no changes in these 2 pages cause they are showing same things so UI should be same, If anything should change then please let me know

![Screenshot (214)](https://user-images.githubusercontent.com/46483236/106890211-015d6380-670f-11eb-9a1e-aeebf14ee545.png)

**Comment by jatinjain001** [comment]
![Screenshot (215)](https://user-images.githubusercontent.com/46483236/106894948-a418e080-6715-11eb-8eb5-9ee2836bb655.png)
this one changes in women laws page

**Comment by swapnilsparsh** [comment]
> ![Screenshot (215)](https://user-images.githubusercontent.com/46483236/106894948-a418e080-6715-11eb-8eb5-9ee2836bb655.png)
> this one changes in women laws page

It's looking messy , try something else.

**Comment by jatinjain001** [comment]
> Changed the UI of helpline numbers, I am bit confused regarding laws and right page . In my view there should be no changes in these 2 pages cause they are showing same things so UI should be same, If anything should change then please let me know
> 
> ![Screenshot (214)](https://user-images.githubusercontent.com/46483236/106890211-015d6380-670f-11eb-9a1e-aeebf14ee545.png)

what about this one

**Comment by swapnilsparsh** [comment]
> > Changed the UI of helpline numbers, I am bit confused regarding laws and right page . In my view there should be no changes in these 2 pages cause they are showing same things so UI should be same, If anything should change then please let me know
> > ![Screenshot (214)](https://user-images.githubusercontent.com/46483236/106890211-015d6380-670f-11eb-9a1e-aeebf14ee545.png)
> 
> what about this one

It's not looking neat, use some UI/UX

**Comment by jatinjain001** [comment]
![Screenshot (221)](https://user-images.githubusercontent.com/46483236/107121768-33f78f80-68ba-11eb-8a05-56bf835368a7.png)
I tried different things I am getting more confused in two pages laws and rights, I think helpline number should be look like this

**Comment by jatinjain001** [comment]
I am working on this, and I did 2 page updated. kindly open this issue again I will give my PR till tomorrow 00:00am ,
