### ISSUE TITLE
FIx the Register page footer

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#83]
![Annotation 2021-01-27 231047](https://user-images.githubusercontent.com/69387608/106031840-c0a19100-60f5-11eb-8847-4eddd4576ecd.png)

**Comment by jatiinyadav** [comment]
Hey @swapnilsparsh,
I would like to work on this issue.

**Comment by sakshikhachane** [comment]
@swapnilsparsh I would like to work on this issue. I will resolve this issue tomorrow itself.

**Comment by jatinjain001** [comment]
I would like to work on it
