### ISSUE TITLE
Fix the Carousel speed

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Rescue#9]

**Comment by sourav-coder** [comment]
Assign this to me

**Comment by patel-atul** [comment]
hey @swapnilsparsh this site is using w3.css framework shoul i have to work with that or I can write my own css for styling.
also can i create a stylesheet for all the css

**Comment by abhinav-huria** [comment]
I want to work on this

**Comment by swapnilsparsh** [comment]
> I want to work on this

OK

**Comment by swapnilsparsh** [comment]
Issue has been resolved by @abhinav-huria
