### ISSUE TITLE
404 error - Page not found

### ISSUE THREAD

**Issue by sakshikhachane** [swapnilsparsh/Rescue#98]
**Is your feature request related to a problem? Please describe.**
----
Adding 404 error page - page not found for the links that are not existing.

**Comment by sakshikhachane** [comment]
@swapnilsparsh Please assign me this issue.

**Comment by swapnilsparsh** [comment]
> ## **Is your feature request related to a problem? Please describe.**
> Adding 404 error - page not found for the links that are not existing.

Can you tell which links are not working ?

**Comment by sakshikhachane** [comment]
@swapnilsparsh Every website is having a `404 error` page for the links randomly inserted by the users. Rather than displaying all the paths. I think there should be some page that will tell the user that the URL link or path that they have entered is wrong.
Below is the image for the same and should be modified.

<img width="702" alt="404" src="https://user-images.githubusercontent.com/53635792/107402469-fd27b080-6b29-11eb-8774-f201e1f9c0cb.PNG">

**Comment by sakshikhachane** [comment]
@swapnilsparsh Should I move ahead with this issue or should I close this issue?
